<?php

/**
 * Customizer string configuration — single source of truth for all theme text.
 */
function developer_theme_customizer_config()
{
    $year = gmdate('Y');

    return [
        'shared' => [
            'name'              => 'Your Name',
            'job_title'         => 'Independent Product Consultant',
            'email'             => 'hello@example.com',
            'linkedin_url'      => 'https://www.linkedin.com/in/yourprofile/',
            'linkedin_display'  => 'linkedin.com/in/yourprofile',
            'github_url'        => 'https://github.com/yourusername',
            'github_display'    => 'github.com/yourusername',
            'telegram_url'      => 'https://t.me/yourusername',
            'telegram_display'  => '@yourusername',
            'location'          => 'Your City, Country',
            'cv_pdf_url'        => '/app/uploads/cv.pdf',
            'profile_image_url' => '/app/uploads/profile.jpg',
            'og_image_url'      => '/app/uploads/og-image.jpg',
            'map_embed_url'     => 'https://www.openstreetmap.org/export/embed.html?bbox=-0.2%2C51.4%2C0.1%2C51.6&layer=mapnik&marker=51.5%2C-0.1',
        ],
        'nav' => [
            'en' => [
                'brand'       => 'Your Name',
                'home'        => 'Home',
                'services'    => 'Services',
                'articles'    => 'Articles',
                'portfolio'   => 'Work',
                'contact'     => 'Contact',
                'footer_text' => 'A neutral starter for showcasing services, selected work, writing, and contact details.',
                'footer_copy' => '&copy; ' . $year . ' Your Name. All rights reserved.',
            ],
            'ru' => [
                'brand'       => 'Ваше имя',
                'home'        => 'Главная',
                'services'    => 'Услуги',
                'articles'    => 'Статьи',
                'portfolio'   => 'Портфолио',
                'contact'     => 'Контакты',
                'footer_text' => 'Нейтральный starter для услуг, кейсов, статей и контактной информации.',
                'footer_copy' => '&copy; ' . $year . ' Ваше имя. Все права защищены.',
            ],
            'uk' => [
                'brand'       => 'Ваше Ім\'я',
                'home'        => 'Головна',
                'articles'    => 'Статті',
                'portfolio'   => 'Портфоліо',
                'contact'     => 'Контакти',
                'footer_text' => 'Нейтральний starter для послуг, кейсів, статей і контактної інформації.',
                'footer_copy' => '&copy; ' . $year . ' Ваше Ім\'я. Усі права захищені.',
            ],
            'es' => [
                'brand'       => 'Your Name',
                'home'        => 'Inicio',
                'articles'    => 'Artículos',
                'portfolio'   => 'Portafolio',
                'contact'     => 'Contacto',
                'footer_text' => 'Portafolio multilingüe, casos prácticos y artículos.',
                'footer_copy' => '&copy; ' . $year . ' Your Name. Todos los derechos reservados.',
            ],
        ],
        'templates' => [
            'front' => [
                'en' => [
                    'hero_eyebrow'     => 'Your Name &middot; Independent Product Consultant',
                    'hero_h1'          => 'Helping teams present services, work, and expertise with a clean multilingual portfolio site.',
                    'hero_lead'        => 'Use this starter to explain what you do, show selected projects, publish articles, and give visitors a clear path to contact you.',
                    'hero_summary'     => 'All copy below is intentionally neutral and can be replaced section by section in the Customizer or via WordPress content.',
                    'cta_book'         => 'Start a conversation',
                    'cta_services'     => 'Explore sections',
                    'cta_project'      => 'Discuss a project',
                    'cta_portfolio'    => 'View work',
                    'cta_cv'           => 'Download CV',
                    'stat1_num'        => '3 core areas',
                    'stat1_label'      => 'services, case studies, and writing',
                    'stat2_num'        => 'Fast setup',
                    'stat2_label'      => 'Docker, demo content, and multilingual structure included',
                    'stat3_num'        => 'Easy edits',
                    'stat3_label'      => 'most text can be updated without touching templates',
                    'focus_label'      => 'Starter note',
                    'focus_text'       => 'This demo is generic by design so it can fit consulting, development, design, or small studio work.',

                    'problems_eye'     => 'Common challenges',
                    'problems_h2'      => 'What this starter helps you communicate',
                    'problems_intro'   => 'Use this area to describe the situations where your service is most useful, so visitors immediately understand whether they are in the right place.',
                    'problem1_h3'      => 'You need a clear offer',
                    'problem1_p'       => 'Explain the problem you solve, who you solve it for, and what kind of outcome a client or employer can expect.',
                    'problem2_h3'      => 'You want proof, not just claims',
                    'problem2_p'       => 'Show relevant projects, a concise process, and practical examples that make your experience feel concrete.',
                    'problem3_h3'      => 'You need a site that is easy to maintain',
                    'problem3_p'       => 'This starter is meant to be updated in WordPress without rebuilding the layout every time your positioning changes.',
                    'expertise_eye'    => 'Expertise',
                    'expertise_h2'     => 'What to highlight here',
                    'expertise_intro'  => 'These cards work well for your main capabilities. Keep them broad enough to be understood quickly, but specific enough to feel credible.',
                    'exp_back_tag'     => 'Strategy',
                    'exp_back_h3'      => 'Positioning and offer clarity.',
                    'exp_back_p'       => 'Describe the type of work you take on, the audience you serve, and the outcomes you aim to deliver.',
                    'exp_front_tag'    => 'Content',
                    'exp_front_h3'      => 'Pages that explain your value without clutter.',
                    'exp_front_p'      => 'Use clear headings, short summaries, and structured sections to make your site easy to scan.',
                    'exp_perf_tag'     => 'Delivery',
                    'exp_perf_h3'      => 'A setup that is simple to update.',
                    'exp_perf_p'       => 'This starter keeps most day-to-day edits in WordPress so the site can evolve without constant code changes.',
                    'exp_del_tag'      => 'Credibility',
                    'exp_del_h3'       => 'Proof through selected work and writing.',
                    'exp_del_p'        => 'Case studies, articles, and a concise process help visitors understand how you think and what you can deliver.',
                    'impact_eye'       => 'Impact',
                    'impact_h2'        => 'Example outcomes',
                    'impact_intro'     => 'Replace these with real results, concise proof points, or testimonials. Until then, they work as structure for the kind of evidence worth showing.',
                    'impact_items'     => [
                        'Clarified an offer so the website immediately explained who it was for and what problems it solved.',
                        'Reworked the structure of a service site so visitors could move from introduction to proof to contact without confusion.',
                        'Turned scattered project notes into concise case studies with outcomes, process, and scope.',
                        'Set up a multilingual portfolio so the same structure could support English, Russian, and Ukrainian content.',
                        'Reduced maintenance overhead by moving routine edits from templates into WordPress-managed fields and content.',
                    ],
                    'experience_eye'   => 'Experience',
                    'experience_h2'    => 'Background examples',
                    'experience_intro' => 'This timeline is useful for roles, major phases, or representative chapters of your work. Keep each entry brief and outcome-oriented.',
                    'role1_tag'        => 'Current',
                    'role1_h3'         => 'Independent consultant or studio lead',
                    'role1_p'          => 'A short summary of the work you do today, the clients or teams you support, and the value you are known for.',
                    'role2_tag'        => 'Previous',
                    'role2_h3'         => 'In-house product or agency role',
                    'role2_p'          => 'An example of prior experience that shows delivery scope, collaboration style, and the kind of projects you handled.',
                    'role3_tag'        => 'Earlier',
                    'role3_h3'         => 'Freelance or foundational work',
                    'role3_p'          => 'Use this slot for the period that shaped your approach, craft, or specialisation.',
                    'stack_eye'        => 'Stack',
                    'stack_h2'         => 'Core technologies',
                    'stack_intro'      => 'I prefer straightforward tools and clear architecture over fashionable complexity. The stack should help the product move faster, not become the product.',
                    'stack_items'      => [ 'Laravel', 'PHP', 'React', 'Vue.js', 'TypeScript', 'JavaScript', 'MySQL', 'PostgreSQL', 'Redis', 'Docker', 'AWS', 'GitHub Actions', 'REST APIs', 'Stripe', 'WordPress', 'PHPUnit', 'Jest', 'Node.js' ],
                    'approach_eye'     => 'Approach',
                    'approach_h2'      => 'How I work',
                    'approach_intro'   => 'I care about the outcome, not just the output. Simple solutions that scale well, clear communication, and engineering decisions that stay maintainable over time.',
                    'approach_items'   => [
                        'Comfortable working independently and in distributed teams',
                        'Strong ownership from architecture to production deployment',
                        'Pragmatic about trade-offs — ship, learn, iterate',
                        'Clear technical communication with both engineers and stakeholders',
                        'Continuous improvement without chasing hype',
                    ],
                    'portfolio_eye'    => 'Portfolio',
                    'portfolio_h2'     => 'Selected work',
                    'portfolio_intro'  => 'Use a small set of case studies that represent your strongest work, your preferred clients, or the type of projects you want more of.',
                    'services_eye'     => 'Services',
                    'services_h2'     => 'How you might structure offers',
                    'services_intro'  => 'These sample cards show one simple way to package services. Adapt the labels, scope, and pricing model to your own work.',
                    'svc1_tag'        => 'Discovery',
                    'svc1_h3'         => 'Audit, review, or planning session',
                    'svc1_p'          => 'A focused engagement for understanding the current situation, identifying priorities, and agreeing on next steps.',
                    'svc1_cta'        => 'Learn more',
                    'svc2_tag'        => 'Implementation',
                    'svc2_h3'         => 'Website, content, or feature delivery',
                    'svc2_p'          => 'A defined build phase where strategy turns into real pages, assets, templates, or systems that can be used immediately.',
                    'svc2_cta'        => 'Learn more',
                    'svc3_tag'        => 'Support',
                    'svc3_h3'         => 'Refinement, launch, and follow-up',
                    'svc3_p'          => 'Post-launch iteration, cleanup, QA, and incremental improvements once the initial structure is in place.',
                    'svc3_cta'        => 'Learn more',

                    'process_eye'     => 'Process',
                    'process_h2'      => 'A simple working process',
                    'process_intro'   => 'Use this section to show how an engagement moves from first contact to delivery. Simple beats over-explained.',
                    'step1_num'       => '01',
                    'step1_h3'        => 'Initial conversation',
                    'step1_p'         => 'Clarify goals, context, constraints, and whether the project is a good fit.',
                    'step2_num'       => '02',
                    'step2_h3'        => 'Scope and priorities',
                    'step2_p'         => 'Turn the discussion into a practical plan with a clear direction, deliverables, or next milestone.',
                    'step3_num'       => '03',
                    'step3_h3'        => 'Delivery and iteration',
                    'step3_p'         => 'Ship the work, gather feedback, and refine what needs another pass.',
                    'proof_eye'       => 'Sample logos',
                    'proof_names'     => [ 'Client A', 'Client B', 'Client C', 'Client D', 'Client E' ],
                    'writing_eye'      => 'Writing',
                    'writing_h2'       => 'Articles or notes',
                    'writing_intro'    => 'Use the blog to publish thoughts, explain your process, or show how you approach the kind of work you want to attract.',
                    'contact_eye'      => 'Get started',
                    'contact_h2'       => 'Ready to make this your own?',
                    'contact_intro'    => 'Replace this sample text with your real call to action, preferred contact method, and response expectations.',
                    'contact_cta'      => 'Send a message',
                    'contact_cta_book' => 'Start a conversation',
                ],
                'ru' => [
                    'hero_eyebrow'     => 'Ваше имя &middot; Независимый продуктовый консультант',
                    'hero_h1'          => 'Помогает командам ясно показать услуги, кейсы и экспертизу на аккуратном мультиязычном сайте.',
                    'hero_lead'        => 'Этот starter можно использовать, чтобы рассказать о себе, показать избранные проекты, публиковать статьи и направлять посетителя к контакту.',
                    'hero_summary'     => 'Тексты ниже сделаны нейтральными специально, чтобы их можно было быстро заменить под свои задачи и позиционирование.',
                    'cta_book'         => 'Начать разговор',
                    'cta_services'     => 'Посмотреть разделы',
                    'cta_project'      => 'Обсудить проект',
                    'cta_portfolio'    => 'Портфолио',
                    'cta_cv'           => 'Скачать CV',
                    'stat1_num'        => '3 ключевых блока',
                    'stat1_label'      => 'услуги, кейсы и статьи',
                    'stat2_num'        => 'Быстрый старт',
                    'stat2_label'      => 'Docker, демо-контент и языковая структура уже есть',
                    'stat3_num'        => 'Просто редактировать',
                    'stat3_label'      => 'большинство текстов меняются без правки шаблонов',
                    'focus_label'      => 'Примечание',
                    'focus_text'       => 'Демо намеренно нейтральное, поэтому подходит для консультанта, разработчика, дизайнера или небольшой студии.',
                    'problems_eye'     => 'Типовые задачи',
                    'problems_h2'      => 'Что этот starter помогает объяснить',
                    'problems_intro'   => 'Используйте этот блок, чтобы быстро показать, для каких ситуаций и клиентов ваш подход подходит лучше всего.',
                    'problem1_h3'      => 'Нужно чётко сформулировать предложение',
                    'problem1_p'       => 'Посетитель должен быстро понять, что именно вы делаете, кому помогаете и к какому результату ведёте.',
                    'problem2_h3'      => 'Нужны доказательства, а не общие слова',
                    'problem2_p'       => 'Кейсы, статьи и структура процесса делают опыт более убедительным, чем длинные абстрактные обещания.',
                    'problem3_h3'      => 'Сайт должен легко обновляться',
                    'problem3_p'       => 'Starter рассчитан на то, чтобы основную часть правок можно было делать через WordPress, без постоянных изменений в шаблонах.',
                    'expertise_eye'    => 'Экспертиза',
                    'expertise_h2'     => 'Что можно подчеркнуть',
                    'expertise_intro'  => 'Эти карточки подойдут для ваших сильных сторон: стратегии, контента, реализации или сопровождения. Формулируйте коротко и понятно.',
                    'exp_back_tag'     => 'Позиционирование',
                    'exp_back_h3'      => 'Чёткое описание вашего предложения.',
                    'exp_back_p'       => 'Объясните, с какими задачами вы помогаете, кому именно и какой результат человек или команда получат в итоге.',
                    'exp_front_tag'    => 'Контент',
                    'exp_front_h3'     => 'Страницы, которые легко читать и сканировать.',
                    'exp_front_p'      => 'Короткие блоки, понятные заголовки и аккуратная структура помогают посетителю быстро понять, что ему предлагают.',
                    'exp_perf_tag'     => 'Поддержка',
                    'exp_perf_h3'      => 'Сайт, который просто обновлять.',
                    'exp_perf_p'       => 'Основную часть правок можно вносить через WordPress, поэтому контент не упирается в постоянные изменения шаблонов.',
                    'exp_del_tag'      => 'Доверие',
                    'exp_del_h3'       => 'Кейсы, статьи и понятный процесс.',
                    'exp_del_p'        => 'Покажите избранные проекты, заметки и этапы работы, чтобы посетитель видел не обещания, а подтверждение подхода.',
                    'impact_eye'       => 'Результаты',
                    'impact_h2'        => 'Примеры результата',
                    'impact_intro'     => 'Пока здесь можно держать нейтральные примеры. Позже замените их на реальные результаты, отзывы или цифры.',
                    'impact_items'     => [
                        'Сделали предложение понятным с первого экрана: кому оно подходит, какую задачу решает и чем отличается.',
                        'Перестроили структуру сайта так, чтобы посетитель без лишних шагов переходил от знакомства к кейсам и контакту.',
                        'Собрали разрозненные материалы в аккуратные кейсы с задачей, объёмом работ и результатом.',
                        'Подготовили мультиязычную структуру, чтобы один и тот же сайт было удобно вести на нескольких языках.',
                        'Упростили регулярные обновления, перенеся рутинные правки из шаблонов в поля и контент WordPress.',
                    ],
                    'experience_eye'   => 'Опыт',
                    'experience_h2'    => 'Пример структуры опыта',
                    'experience_intro' => 'Эта временная шкала подходит для ролей, важных этапов работы или карьерных периодов. Делайте формулировки короткими и ориентированными на результат.',
                    'role1_tag'        => 'Текущий этап',
                    'role1_h3'         => 'Основная роль или направление работы',
                    'role1_p'          => 'Коротко опишите, чем вы занимаетесь сейчас, с какими людьми или командами работаете и за что вас чаще всего рекомендуют.',
                    'role2_tag'        => 'Предыдущий этап',
                    'role2_h3'         => 'Роль в продукте, студии или агентстве',
                    'role2_p'          => 'Используйте этот блок, чтобы показать масштаб задач, стиль взаимодействия и тип проектов, с которыми у вас уже был опыт.',
                    'role3_tag'        => 'Ранее',
                    'role3_h3'         => 'Фриланс, первые проекты или становление практики',
                    'role3_p'          => 'Здесь хорошо смотрится период, который сформировал ваш подход, специализацию и способ работать с клиентами.',
                    'stack_eye'        => 'Инструменты',
                    'stack_h2'         => 'Основные инструменты',
                    'stack_intro'      => 'Укажите инструменты, платформы или категории технологий, которые действительно важны для вашей работы и понятны аудитории.',
                    'stack_items'      => [ 'WordPress', 'Custom Themes', 'Content Strategy', 'Case Studies', 'SEO Basics', 'Multilingual Setup', 'Design Systems', 'Analytics', 'Forms', 'Performance', 'Docker', 'GitHub', 'Project Discovery', 'Editorial Workflow' ],
                    'approach_eye'     => 'Подход',
                    'approach_h2'      => 'Как вы можете описать процесс',
                    'approach_intro'   => 'Этот блок нужен для короткого объяснения принципов работы: как вы принимаете решения, как общаетесь и за что отвечаете.',
                    'approach_items'   => [
                        'Понятные ожидания по срокам, объёму и следующим шагам',
                        'Простые решения вместо лишней сложности',
                        'Регулярная обратная связь без затянутых циклов согласования',
                        'Чёткая коммуникация с командой и заказчиком',
                        'Фокус на результате, а не на количестве артефактов',
                    ],
                    'portfolio_eye'    => 'Портфолио',
                    'portfolio_h2'     => 'Избранные продуктовые и платформенные работы',
                    'portfolio_intro'  => 'Эти кейсы показывают мою сильнейшую работу: продуктовая инженерия, структурированный контент и реализация, которая остаётся поддерживаемой после запуска.',
                    'services_eye'     => 'Услуги',
                    'services_h2'     => 'Как можно упаковать услуги',
                    'services_intro'  => 'Эти карточки показывают нейтральный способ описать предложения. Подставьте свои форматы работы, объём и условия.',
                    'svc1_tag'        => 'Аудит',
                    'svc1_h3'         => 'Разбор текущей ситуации',
                    'svc1_p'          => 'Короткий формат для диагностики, приоритизации задач и определения понятного следующего шага.',
                    'svc2_tag'        => 'Реализация',
                    'svc2_h3'         => 'Сборка сайта, раздела или контентной системы',
                    'svc2_p'          => 'Основной этап работы, где стратегия превращается в реальные страницы, тексты, шаблоны и материалы для запуска.',
                    'svc3_tag'        => 'Поддержка',
                    'svc3_h3'         => 'Доработки после запуска',
                    'svc3_p'          => 'QA, мелкие улучшения, донастройка и помощь после релиза, когда базовая структура уже работает.',
                    'svc4_tag'        => 'Опция',
                    'svc4_h3'         => 'Дополнительный пакет или сопровождение',
                    'svc4_p'          => 'При необходимости можно описать ретейнер, обучение команды, редакторскую поддержку или другой повторяющийся формат.',
                    'proof_eye'       => 'Работал с',
                    'proof_names'     => [ 'Client A', 'Client B', 'Client C', 'Client D', 'Client E' ],
                    'writing_eye'      => 'Статьи',
                    'writing_h2'       => 'Статьи на основе реальных проектов',
                    'writing_intro'    => 'Используйте блог для заметок, разборов, мыслей о процессе или публикаций, которые помогают понять ваш подход к работе.',
                    'contact_eye'      => 'Контакты',
                    'contact_h2'       => 'Готовы адаптировать starter под себя?',
                    'contact_intro'    => 'Замените этот блок на свой реальный call to action, удобный канал связи и ожидания по ответу.',
                    'contact_cta'      => 'Написать сообщение',
                    'contact_cta_book' => 'Начать разговор',
                ],
                'uk' => [
                    'hero_eyebrow'     => 'Ваше Ім\'я &middot; Незалежний продуктовий консультант',
                    'hero_h1'          => 'Допомагає командам чітко показати послуги, кейси та експертизу на охайному багатомовному сайті.',
                    'hero_lead'        => 'Цей starter можна використати, щоб розповісти про себе, показати вибрані проєкти, публікувати статті та вести відвідувача до контакту.',
                    'hero_summary'     => 'Тексти нижче зроблені нейтральними спеціально, щоб їх можна було швидко замінити під власне позиціонування.',
                    'cta_book'         => 'Почати розмову',
                    'cta_services'     => 'Переглянути розділи',
                    'cta_project'      => 'Обговорити проєкт',
                    'cta_portfolio'    => 'Портфоліо',
                    'cta_cv'           => 'Завантажити CV',
                    'stat1_num'        => '3 ключові блоки',
                    'stat1_label'      => 'послуги, кейси та статті',
                    'stat2_num'        => 'Швидкий старт',
                    'stat2_label'      => 'Docker, демо-контент і мовна структура вже налаштовані',
                    'stat3_num'        => 'Просто редагувати',
                    'stat3_label'      => 'більшість текстів можна змінювати без правки шаблонів',
                    'focus_label'      => 'Примітка',
                    'focus_text'       => 'Демо навмисно нейтральне, тому підходить для консультанта, розробника, дизайнера або невеликої студії.',
                    'problems_eye'     => 'Типові задачі',
                    'problems_h2'      => 'Що цей starter допомагає пояснити',
                    'problems_intro'   => 'Використовуйте цей блок, щоб швидко показати, для яких ситуацій і клієнтів ваш підхід підходить найкраще.',
                    'problem1_h3'      => 'Потрібно чітко сформулювати пропозицію',
                    'problem1_p'       => 'Відвідувач має швидко зрозуміти, що саме ви робите, кому допомагаєте та до якого результату ведете.',
                    'problem2_h3'      => 'Потрібні докази, а не загальні слова',
                    'problem2_p'       => 'Кейси, статті та структура процесу роблять досвід переконливішим за довгі абстрактні обіцянки.',
                    'problem3_h3'      => 'Сайт має легко оновлюватися',
                    'problem3_p'       => 'Starter розрахований на те, щоб основну частину правок можна було робити через WordPress, без постійних змін у шаблонах.',
                    'expertise_eye'    => 'Експертиза',
                    'expertise_h2'     => 'Що можна підкреслити',
                    'expertise_intro'  => 'Ці картки підійдуть для ваших сильних сторін: стратегії, контенту, реалізації або супроводу. Формулюйте коротко й зрозуміло.',
                    'exp_back_tag'     => 'Позиціювання',
                    'exp_back_h3'      => 'Чіткий опис вашої пропозиції.',
                    'exp_back_p'       => 'Поясніть, у яких ситуаціях ви допомагаєте, кому саме і який результат людина або команда отримають у підсумку.',
                    'exp_front_tag'    => 'Контент',
                    'exp_front_h3'     => 'Сторінки, які легко читати й переглядати.',
                    'exp_front_p'      => 'Короткі блоки, зрозумілі заголовки та акуратна структура допомагають відвідувачу швидко зрозуміти суть пропозиції.',
                    'exp_perf_tag'     => 'Підтримка',
                    'exp_perf_h3'      => 'Сайт, який легко оновлювати.',
                    'exp_perf_p'       => 'Основну частину змін можна вносити через WordPress, тому контент не залежить від постійного редагування шаблонів.',
                    'exp_del_tag'      => 'Довіра',
                    'exp_del_h3'       => 'Кейси, статті та зрозумілий процес.',
                    'exp_del_p'        => 'Покажіть вибрані проєкти, нотатки та етапи роботи, щоб відвідувач бачив не обіцянки, а підтвердження підходу.',
                    'impact_eye'       => 'Результати',
                    'impact_h2'        => 'Приклади результату',
                    'impact_intro'     => 'Поки тут можна залишити нейтральні приклади. Згодом замініть їх на реальні результати, цифри або відгуки.',
                    'impact_items'     => [
                        'Зробили пропозицію зрозумілою з першого екрана: кому вона підходить, яку задачу вирішує та чим відрізняється.',
                        'Перебудували структуру сайту так, щоб відвідувач без зайвих кроків переходив від знайомства до кейсів і контакту.',
                        'Зібрали розрізнені матеріали в акуратні кейси із задачею, обсягом робіт і результатом.',
                        'Підготували багатомовну структуру, щоб один і той самий сайт було зручно вести кількома мовами.',
                        'Спростили регулярні оновлення, перенісши рутинні правки з шаблонів у поля та контент WordPress.',
                    ],
                    'experience_eye'   => 'Досвід',
                    'experience_h2'    => 'Приклад структури досвіду',
                    'experience_intro' => 'Ця шкала часу добре підходить для ролей, важливих етапів роботи або професійних періодів. Формулюйте коротко й через результат.',
                    'role1_tag'        => 'Поточний етап',
                    'role1_h3'         => 'Основна роль або напрям роботи',
                    'role1_p'          => 'Коротко опишіть, чим займаєтесь зараз, з ким працюєте та за що вас найчастіше рекомендують.',
                    'role2_tag'        => 'Попередній етап',
                    'role2_h3'         => 'Роль у продукті, студії або агенції',
                    'role2_p'          => 'Використайте цей блок, щоб показати масштаб задач, стиль співпраці та тип проєктів, з якими ви вже працювали.',
                    'role3_tag'        => 'Раніше',
                    'role3_h3'         => 'Фриланс, перші проєкти або формування практики',
                    'role3_p'          => 'Тут добре виглядає період, який сформував ваш підхід, спеціалізацію та спосіб працювати з клієнтами.',
                    'stack_eye'        => 'Інструменти',
                    'stack_h2'         => 'Основні інструменти',
                    'stack_intro'      => 'Зазначте інструменти, платформи або категорії технологій, які справді важливі для вашої роботи й зрозумілі аудиторії.',
                    'stack_items'      => [ 'WordPress', 'Custom Themes', 'Content Strategy', 'Case Studies', 'SEO Basics', 'Multilingual Setup', 'Design Systems', 'Analytics', 'Forms', 'Performance', 'Docker', 'GitHub', 'Project Discovery', 'Editorial Workflow' ],
                    'approach_eye'     => 'Підхід',
                    'approach_h2'      => 'Як можна описати процес',
                    'approach_intro'   => 'Цей блок потрібен для короткого пояснення принципів роботи: як ви ухвалюєте рішення, як комунікуєте та за що відповідаєте.',
                    'approach_items'   => [
                        'Зрозумілі очікування щодо строків, обсягу та наступних кроків',
                        'Прості рішення замість зайвої складності',
                        'Регулярний зворотний зв\'язок без затягнутих циклів погодження',
                        'Чітка комунікація з командою та замовником',
                        'Фокус на результаті, а не на кількості артефактів',
                    ],
                    'portfolio_eye'    => 'Портфоліо',
                    'portfolio_h2'     => 'Обрані продуктові та платформні роботи',
                    'portfolio_intro'  => 'Ці кейси показують мою найсильнішу роботу: продуктова інженерія, структурований контент та реалізація, що залишається підтримуваною після запуску.',
                    'services_eye'     => 'Послуги',
                    'services_h2'     => 'Як можна оформити послуги',
                    'services_intro'  => 'Ці картки показують нейтральний спосіб описати пропозицію. Підставте свої формати співпраці, обсяг і умови.',
                    'svc1_tag'        => 'Аудит',
                    'svc1_h3'         => 'Розбір поточної ситуації',
                    'svc1_p'          => 'Короткий формат для діагностики, пріоритизації задач і визначення зрозумілого наступного кроку.',
                    'svc2_tag'        => 'Реалізація',
                    'svc2_h3'         => 'Збірка сайту, розділу або контентної системи',
                    'svc2_p'          => 'Основний етап роботи, де стратегія перетворюється на реальні сторінки, тексти, шаблони та матеріали для запуску.',
                    'svc3_tag'        => 'Підтримка',
                    'svc3_h3'         => 'Доопрацювання після запуску',
                    'svc3_p'          => 'QA, дрібні покращення, донастроювання та допомога після релізу, коли базова структура вже працює.',
                    'svc4_tag'        => 'Опція',
                    'svc4_h3'         => 'Додатковий пакет або супровід',
                    'svc4_p'          => 'За потреби тут можна описати ретейнер, навчання команди, редакторську підтримку або інший повторюваний формат.',
                    'proof_eye'       => 'Працював з',
                    'proof_names'     => [ 'Client A', 'Client B', 'Client C', 'Client D', 'Client E' ],
                    'writing_eye'      => 'Статті',
                    'writing_h2'       => 'Статті на основі реальних проєктів',
                    'writing_intro'    => 'Використовуйте блог для нотаток, розборів, думок про процес або матеріалів, які пояснюють ваш підхід до роботи.',
                    'contact_eye'      => 'Контакти',
                    'contact_h2'       => 'Готові адаптувати starter під себе?',
                    'contact_intro'    => 'Замініть цей блок на свій реальний call to action, зручний канал зв\'язку та очікування щодо відповіді.',
                    'contact_cta'      => 'Написати повідомлення',
                    'contact_cta_book' => 'Почати розмову',
                ],
                'es' => [
                    'hero_eyebrow'     => 'Your Name &middot; Independent Consultant',
                    'hero_h1'          => 'Construyendo productos web escalables con arquitectura backend sólida.',
                    'hero_lead'        => 'Diseño y entrego sistemas SaaS confiables, herramientas internas y funcionalidades de producto con Laravel, React, Vue.js, TypeScript, MySQL, AWS, Docker y CI/CD.',
                    'hero_summary'     => 'Con más de 10 años de experiencia práctica, ayudo a equipos a modernizar código heredado, mejorar el rendimiento en producción y entregar software mantenible sin perder impulso de producto.',
                    'cta_project'      => 'Hablemos de tu proyecto',
                    'cta_portfolio'    => 'Ver portafolio',
                    'cta_cv'           => 'Descargar CV',
                    'stat1_num'        => '10+ años',
                    'stat1_label'      => 'entregando sistemas web en producción',
                    'stat2_num'        => 'Full-stack',
                    'stat2_label'      => 'backend, frontend y ownership de entrega',
                    'stat3_num'        => 'Enfoque SaaS',
                    'stat3_label'      => 'apps escalables, facturación, rendimiento',
                    'focus_label'      => 'Enfoque actual',
                    'focus_text'       => 'Arquitectura Laravel, ingeniería de producto, integraciones escalables y flujos de entrega prácticos.',
                    'expertise_eye'    => 'Experiencia',
                    'expertise_h2'     => 'Qué hago',
                    'expertise_intro'  => 'Trabajo mejor en productos que necesitan más que tareas aisladas: decisiones de backend, implementación frontend, entrega confiable y resultados de negocio medibles.',
                    'exp_back_tag'     => 'Backend',
                    'exp_back_h3'      => 'Sistemas Laravel que se mantienen escalables.',
                    'exp_back_p'       => 'Límites de servicio, colas, caché, flujos de facturación, integraciones limpias y rutas de código predecibles para uso real en producción.',
                    'exp_front_tag'    => 'Frontend',
                    'exp_front_h3'     => 'Interfaces prácticas para dashboards y herramientas internas.',
                    'exp_front_p'      => 'Implementaciones con React, Vue.js y TypeScript enfocadas en claridad, rendimiento y los flujos que los equipos necesitan cada día.',
                    'exp_perf_tag'     => 'Rendimiento',
                    'exp_perf_h3'      => 'Optimización que mejora la experiencia real del usuario.',
                    'exp_perf_p'       => 'Ajuste de consultas, indexación de BD, Redis, tareas en segundo plano y decisiones de infraestructura que eliminan cuellos de botella en vez de ocultarlos.',
                    'exp_del_tag'      => 'Entrega',
                    'exp_del_h3'       => 'Releases más seguros y mejor flujo de ingeniería.',
                    'exp_del_p'        => 'Docker, AWS, CI/CD, code reviews y disciplina de ingeniería que reducen el overhead manual y dan más confianza al equipo en producción.',
                    'impact_eye'       => 'Impacto',
                    'impact_h2'        => 'Resultados seleccionados',
                    'impact_intro'     => 'El mejor trabajo después del lanzamiento suele parecer aburrido: releases simples, menos incidentes, mejor rendimiento y sistemas más limpios para la siguiente iteración.',
                    'impact_items'     => [
                        'Modernización del deploy: migré releases manuales a pipelines CI/CD automatizados, reduciendo el tiempo de release de horas a minutos.',
                        'Mejoré la capacidad de respuesta en producción mediante optimización de consultas, indexación y caché Redis — reduciendo tiempos de carga hasta un 60% en flujos clave.',
                        'Construí facturación por suscripción con Laravel Cashier y Stripe: cobros recurrentes, pruebas y eventos de ciclo de vida.',
                        'Elevé la calidad de ingeniería a través de reviews, mentoría y cultura de ownership más fuerte en equipos distribuidos.',
                        'Entregué plataformas de contenido multilingüe con más de 100K visitantes mensuales, estructura limpia y arquitectura orientada a SEO.',
                    ],
                    'experience_eye'   => 'Experiencia',
                    'experience_h2'    => 'Trayectoria de ingeniería',
                    'experience_intro' => 'Mi trabajo más fuerte está en la intersección del pensamiento de producto y la implementación: modernización legacy, limpieza de arquitectura, mejora de entrega y features que apoyan objetivos de negocio reales.',
                    'role1_tag'        => '2020 — Presente',
                    'role1_h3'         => 'Rol principal o área de enfoque',
                    'role1_p'          => 'Ingeniería de producto SaaS, entrega frontend, sistemas backend, superficies de contenido e implementación mantenible para una plataforma madura de asistencia de escritura usada por clientes empresariales.',
                    'role2_tag'        => '2016 — 2020',
                    'role2_h3'         => 'Desarrollador Full-Stack en entornos de producto y agencia',
                    'role2_p'          => 'Sistemas Laravel, plataformas WordPress, APIs, facturación, plugins personalizados y herramientas de negocio en diferentes etapas de producto y proyectos de clientes.',
                    'role3_tag'        => '2014 — 2016',
                    'role3_h3'         => 'Desarrollador Web — inicio de carrera y freelance',
                    'role3_p'          => 'Aprendiendo el oficio a través de trabajo real con clientes: temas WordPress personalizados, backends PHP, layouts responsivos y los hábitos que se forman al entregar bajo restricciones.',
                    'stack_eye'        => 'Stack',
                    'stack_h2'         => 'Tecnologías principales',
                    'stack_intro'      => 'Prefiero herramientas directas y arquitectura clara sobre complejidad de moda. El stack debe ayudar al producto a moverse más rápido, no convertirse en el producto.',
                    'stack_items'      => [ 'Laravel', 'PHP', 'React', 'Vue.js', 'TypeScript', 'JavaScript', 'MySQL', 'PostgreSQL', 'Redis', 'Docker', 'AWS', 'GitHub Actions', 'REST APIs', 'Stripe', 'WordPress', 'PHPUnit', 'Jest', 'Node.js' ],
                    'approach_eye'     => 'Enfoque',
                    'approach_h2'      => 'Cómo trabajo',
                    'approach_intro'   => 'Me importa el resultado, no solo el volumen de trabajo. Soluciones simples que escalan bien, comunicación clara y decisiones de ingeniería que se mantienen con el tiempo.',
                    'approach_items'   => [
                        'Cómodo trabajando de forma independiente y en equipos distribuidos',
                        'Fuerte ownership desde la arquitectura hasta el deploy en producción',
                        'Pragmático con los trade-offs — entregar, aprender, iterar',
                        'Comunicación técnica clara tanto con ingenieros como con stakeholders',
                        'Mejora continua sin perseguir tendencias',
                    ],
                    'portfolio_eye'    => 'Portafolio',
                    'portfolio_h2'     => 'Trabajos seleccionados de producto y plataforma',
                    'portfolio_intro'  => 'Estos casos muestran mi mejor trabajo: ingeniería orientada a producto, experiencias de contenido estructurado e implementación que se mantiene después del lanzamiento.',
                    'services_eye'     => 'Servicios',
                    'services_h2'     => 'En qué puedo ayudarte',
                    'services_intro'  => 'Disponible para freelance, contrato y trabajo remoto de producto. Aquí es donde aporto más valor.',
                    'svc1_tag'        => 'SaaS y productos',
                    'svc1_h3'         => 'Ingeniería SaaS y de producto',
                    'svc1_p'          => 'APIs Laravel, facturación y suscripciones, integraciones externas, arquitectura de plataformas y sistemas backend escalables para productos en crecimiento.',
                    'svc2_tag'        => 'WordPress',
                    'svc2_h3'         => 'WordPress personalizado y plugins',
                    'svc2_p'          => 'Temas personalizados, ecosistemas de plugins, plataformas multilingües, WooCommerce y arquitectura de contenido que los editores disfrutan usar.',
                    'svc3_tag'        => 'Rendimiento',
                    'svc3_h3'         => 'Rendimiento y arquitectura',
                    'svc3_p'          => 'Migraciones de plataformas, reconstrucciones legacy, optimización de consultas, estrategia de caché y limpieza de infraestructura para la siguiente iteración.',
                    'svc4_tag'        => 'DevOps',
                    'svc4_h3'         => 'Entrega y CI/CD',
                    'svc4_p'          => 'Entornos Docker, GitHub Actions, deploys automatizados, ownership de releases y disciplina de ingeniería para confianza en producción.',
                    'proof_eye'       => 'He trabajado con',
                    'proof_names'     => [ 'Client A', 'Client B', 'Client C', 'Client D', 'Client E' ],
                    'writing_eye'      => 'Artículos',
                    'writing_h2'       => 'Artículos basados en trabajo real',
                    'writing_intro'    => 'Escribo sobre Laravel, arquitectura, rendimiento e ingeniería práctica. Son notas de proyectos reales — no teoría abstracta.',
                    'contact_eye'      => 'Contacto',
                    'contact_h2'       => '¿Necesitas ayuda con un producto o reconstrucción de plataforma?',
                    'contact_intro'    => 'Si estás mejorando un sistema existente, lanzando algo nuevo o buscas un ingeniero senior que pueda operar en backend, frontend e infraestructura — escríbeme.',
                    'contact_cta'      => 'Enviar un mensaje',
                ],
            ],
            'home' => [
                'en' => [
                    'page_title' => 'Articles',
                    'page_intro' => 'Use this section for articles, notes, case-study breakdowns, or updates that show how you think and how you work.',
                    'read_more'  => 'Read article',
                    'no_posts'   => 'No articles yet. Check back soon.',
                    'older'      => 'Older articles',
                    'newer'      => 'Newer articles',
                ],
                'ru' => [
                    'page_title' => 'Статьи',
                    'page_intro' => 'Используйте этот раздел для статей, заметок, разборов кейсов и публикаций, которые помогают понять ваш подход к работе.',
                    'read_more'  => 'Читать статью',
                    'no_posts'   => 'Статей пока нет. Заходите позже.',
                    'older'      => 'Старые статьи',
                    'newer'      => 'Новые статьи',
                ],
                'uk' => [
                    'page_title' => 'Статті',
                    'page_intro' => 'Використовуйте цей розділ для статей, нотаток, розборів кейсів і матеріалів, які пояснюють ваш підхід до роботи.',
                    'read_more'  => 'Читати статтю',
                    'no_posts'   => 'Статей поки немає. Заходьте пізніше.',
                    'older'      => 'Старіші статті',
                    'newer'      => 'Новіші статті',
                ],
                'es' => [
                    'page_title' => 'Artículos',
                    'page_intro' => 'Notas sobre Laravel, arquitectura, rendimiento e ingeniería práctica. Basadas en proyectos reales, escritas para ingenieros y equipos.',
                    'read_more'  => 'Leer artículo',
                    'no_posts'   => 'Aún no hay artículos. Vuelve pronto.',
                    'older'      => 'Artículos anteriores',
                    'newer'      => 'Artículos más recientes',
                ],
            ],
            'archive_portfolio' => [
                'en' => [
                    'page_title' => 'Portfolio',
                    'page_intro' => 'Product-facing engineering, structured content experiences, and implementation that stays maintainable after launch.',
                    'no_posts'   => 'No portfolio items yet.',
                ],
                'ru' => [
                    'page_title' => 'Портфолио',
                    'page_intro' => 'Продуктовая инженерия, структурированный контент и реализация, которая остаётся поддерживаемой после запуска.',
                    'no_posts'   => 'Портфолио пока пусто.',
                ],
                'uk' => [
                    'page_title' => 'Портфоліо',
                    'page_intro' => 'Продуктова інженерія, структурований контент та реалізація, що залишається підтримуваною після запуску.',
                    'no_posts'   => 'Портфоліо поки порожнє.',
                ],
                'es' => [
                    'page_title' => 'Portafolio',
                    'page_intro' => 'Ingeniería orientada a producto, experiencias de contenido estructurado e implementación que se mantiene después del lanzamiento.',
                    'no_posts'   => 'Aún no hay elementos en el portafolio.',
                ],
            ],
            'contact' => [
                'en' => [
                    'page_title'   => 'Get in touch',
                    'page_intro'   => 'Use this page for your preferred contact method, response expectations, and any short note that helps visitors feel comfortable reaching out.',
                    'form_heading' => 'Send a message',
                    'info_heading' => 'Contact details',
                    'location_lbl' => 'Location',
                    'location'     => 'Your City, Country',
                    'availability' => 'Available for remote or local collaboration.',
                ],
                'ru' => [
                    'page_title'   => 'Связаться',
                    'page_intro'   => 'Используйте эту страницу для удобного способа связи, ожидаемого времени ответа и короткой вводной фразы для посетителя.',
                    'form_heading' => 'Написать сообщение',
                    'info_heading' => 'Контактные данные',
                    'location_lbl' => 'Расположение',
                    'location'     => 'Ваш город, страна',
                    'availability' => 'Доступен для удалённой и локальной работы.',
                ],
                'uk' => [
                    'page_title'   => 'Зв\'язатися',
                    'page_intro'   => 'Використовуйте цю сторінку для зручного способу зв\'язку, очікуваного часу відповіді та короткого вступного повідомлення для відвідувача.',
                    'form_heading' => 'Написати повідомлення',
                    'info_heading' => 'Контактні дані',
                    'location_lbl' => 'Розташування',
                    'location'     => 'Ваше місто, країна',
                    'availability' => 'Доступний для віддаленої та локальної співпраці.',
                ],
                'es' => [
                    'page_title'   => 'Ponte en contacto',
                    'page_intro'   => 'Si tienes un proyecto en mente, necesitas un ingeniero senior para tu equipo, o simplemente quieres saludar — estaré encantado de escucharte.',
                    'form_heading' => 'Enviar un mensaje',
                    'info_heading' => 'Datos de contacto',
                    'location_lbl' => 'Ubicación',
                    'location'     => 'Berlín, Alemania',
                    'availability' => 'Disponible para trabajo remoto a nivel mundial.',
                ],
            ],
            'about' => [
                'en' => [
                    'about_eye'        => 'About',
                    'about_h1'         => 'A short professional introduction',
                    'about_intro'      => 'Use this page to describe your background, the kind of work you enjoy, and the experience you want visitors to notice first.',

                    'bio_h2'           => 'Who I am',
                    'bio_p1'           => 'Start with a clear summary: who you are, where you are based, and what kind of work or clients you focus on.',
                    'bio_p2'           => 'Then add a second paragraph that explains your approach, your strengths, and the type of collaboration people can expect from you.',

                    'exp_h2'           => 'Professional experience',
                    'exp_intro'        => 'Use this timeline for major roles, representative chapters, or the periods that shaped how you work. Keep each entry short and outcome-focused.',
                    'role1_date'       => 'Current',
                    'role1_h3'         => 'Primary role or focus area',
                    'role1_p'          => 'Summarize what you do today, who you work with, and the kind of value or outcomes people usually hire you for.',
                    'role2_date'       => 'Previous',
                    'role2_h3'         => 'In-house, studio, or agency role',
                    'role2_p'          => 'Describe a prior chapter that shows delivery scope, collaboration style, and the type of projects you handled.',
                    'role3_date'       => 'Earlier',
                    'role3_h3'         => 'Freelance, formative work, or early projects',
                    'role3_p'          => 'Use this slot for the period that shaped your craft, your process, or your current specialization.',

                    'stack_h2'         => 'Core tools',
                    'stack_intro'      => 'List the platforms, tools, or categories that matter most to your audience. Keep it readable and useful, not exhaustive.',
                    'about_stack_items' => ['WordPress', 'Custom Themes', 'Content Strategy', 'Case Studies', 'SEO Basics', 'Multilingual Setup', 'Design Systems', 'Analytics', 'Forms', 'Performance', 'Docker', 'GitHub', 'Project Discovery', 'Editorial Workflow'],

                    'approach_h2'      => 'How you work',
                    'approach_intro'   => 'Use this section to explain the principles behind your work: how you communicate, how you make decisions, and what collaborators can expect.',
                    'approach_items'   => [
                        'Clear expectations around scope, timing, and next steps',
                        'Simple solutions before unnecessary complexity',
                        'Regular feedback without drawn-out approval cycles',
                        'Direct communication with both clients and collaborators',
                        'Focus on outcomes rather than volume of deliverables',
                    ],

                    'cta_h2'           => 'Ready to connect?',
                    'cta_p'            => 'End the page with a simple invitation that makes the next step clear and easy.',
                    'cta_book'         => 'Start a conversation',
                    'cta_contact'      => 'Send a message',
                ],
            ],
            'single' => [
                'en' => [
                    'breadcrumbs'      => 'Breadcrumbs',
                    'post_nav'         => 'Post page navigation',
                    'blog_article'     => 'Blog article',
                    'published'        => 'Published',
                    'updated'          => 'Updated',
                    'reading_time'     => 'min read',
                    'toc'              => 'On this page',
                    'recent_posts'     => 'More articles',
                    'cta_eyebrow'      => 'Interested in similar work?',
                    'cta_title'        => 'Use article pages to connect your thinking with the services or projects you want to attract.',
                    'cta_body'         => 'A short call to action here can move readers from content into contact or selected work.',
                    'cta_primary'      => 'Start a conversation',
                    'cta_secondary'    => 'See selected work',
                    'author_title'     => 'About the author',
                    'author_body'      => 'Replace this with a compact author bio that supports the article without turning into a full resume.',
                    'share_title'      => 'Share this article',
                    'next_article'     => 'Next article',
                    'previous_article' => 'Previous article',
                    'explore_more'     => 'Explore more',
                    'footer_text'      => 'Multilingual portfolio, case studies, and technical writing.',
                ],
                'ru' => [
                    'breadcrumbs'      => 'Хлебные крошки',
                    'post_nav'         => 'Навигация по странице статьи',
                    'blog_article'     => 'Статья блога',
                    'published'        => 'Опубликовано',
                    'updated'          => 'Обновлено',
                    'reading_time'     => 'мин чтения',
                    'toc'              => 'Содержание',
                    'recent_posts'     => 'Другие статьи',
                    'cta_eyebrow'      => 'Интересна похожая работа?',
                    'cta_title'        => 'Используйте страницы статей, чтобы связать свои материалы с услугами или проектами, которые хотите привлекать.',
                    'cta_body'         => 'Короткий call to action здесь помогает перевести читателя из контента в контакт или кейсы.',
                    'cta_primary'      => 'Связаться',
                    'cta_secondary'    => 'Смотреть кейсы',
                    'author_title'     => 'Об авторе',
                    'author_body'      => 'Замените этот текст на короткое био автора, которое поддерживает статью и не превращается в длинное резюме.',
                    'share_title'      => 'Поделиться статьей',
                    'next_article'     => 'Следующая статья',
                    'previous_article' => 'Предыдущая статья',
                    'explore_more'     => 'Смотрите также',
                    'footer_text'      => 'Мультиязычное портфолио, кейсы и технические статьи.',
                ],
                'uk' => [
                    'breadcrumbs'      => 'Хлібні крихти',
                    'post_nav'         => 'Навігація сторінкою статті',
                    'blog_article'     => 'Стаття блогу',
                    'published'        => 'Опубліковано',
                    'updated'          => 'Оновлено',
                    'reading_time'     => 'хв читання',
                    'toc'              => 'Зміст',
                    'recent_posts'     => 'Інші статті',
                    'cta_eyebrow'      => 'Цікавить схожа робота?',
                    'cta_title'        => 'Використовуйте сторінки статей, щоб пов\'язати свої матеріали з послугами або проєктами, які хочете залучати.',
                    'cta_body'         => 'Короткий call to action тут допомагає перевести читача з контенту до контакту або кейсів.',
                    'cta_primary'      => 'Зв\'язатися',
                    'cta_secondary'    => 'Переглянути кейси',
                    'author_title'     => 'Про автора',
                    'author_body'      => 'Замініть цей текст на коротке біо автора, яке підтримує статтю й не перетворюється на довге резюме.',
                    'share_title'      => 'Поділитися статтею',
                    'next_article'     => 'Наступна стаття',
                    'previous_article' => 'Попередня стаття',
                    'explore_more'     => 'Дивіться також',
                    'footer_text'      => 'Мультимовне портфоліо, кейси та технічні статті.',
                ],
                'es' => [
                    'breadcrumbs'      => 'Migas de pan',
                    'post_nav'         => 'Navegación de la página del artículo',
                    'blog_article'     => 'Artículo del blog',
                    'published'        => 'Publicado',
                    'updated'          => 'Actualizado',
                    'reading_time'     => 'min de lectura',
                    'toc'              => 'En esta página',
                    'recent_posts'     => 'Más artículos',
                    'cta_eyebrow'      => '¿Necesitas un senior engineer?',
                    'cta_title'        => 'Ayudo a los equipos a modernizar productos, mejorar el rendimiento y lanzar plataformas más limpias.',
                    'cta_body'         => 'Desde arquitectura y backends en Laravel hasta frontend, contenido listo para SEO y flujos de desarrollo.',
                    'cta_primary'      => 'Hablemos',
                    'cta_secondary'    => 'Ver proyectos',
                    'author_title'     => 'Sobre el autor',
                    'author_body'      => 'Sustituye este texto por una biografía breve del autor que complemente el artículo sin convertirse en un currículum completo.',
                    'share_title'      => 'Compartir este artículo',
                    'next_article'     => 'Siguiente artículo',
                    'previous_article' => 'Artículo anterior',
                    'explore_more'     => 'Explorar más',
                    'footer_text'      => 'Portafolio multilingüe, casos prácticos y artículos técnicos.',
                ],
            ],
            'archive' => [
                'en' => [
                    'read_more' => 'Read article',
                    'no_posts'  => 'No articles found in this category.',
                    'older'     => 'Older articles',
                    'newer'     => 'Newer articles',
                ],
                'ru' => [
                    'read_more' => 'Читать статью',
                    'no_posts'  => 'В этой категории пока нет статей.',
                    'older'     => 'Старые статьи',
                    'newer'     => 'Новые статьи',
                ],
                'uk' => [
                    'read_more' => 'Читати статтю',
                    'no_posts'  => 'У цій категорії поки немає статей.',
                    'older'     => 'Старіші статті',
                    'newer'     => 'Новіші статті',
                ],
                'es' => [
                    'read_more' => 'Leer artículo',
                    'no_posts'  => 'No hay artículos en esta categoría.',
                    'older'     => 'Artículos anteriores',
                    'newer'     => 'Artículos más recientes',
                ],
            ],
            'errors' => [
                'en' => [
                    '404_title'         => 'Page not found',
                    '404_text'          => 'The page you are looking for does not exist or has been moved.',
                    'search_eyebrow'    => 'Search results',
                    'search_found'      => 'Found %d results',
                    'search_empty'      => 'No results found for your query.',
                    'search_suggestion' => 'Try a different search term, or explore the links below.',
                ],
                'ru' => [
                    '404_title'         => 'Страница не найдена',
                    '404_text'          => 'Запрашиваемая страница не существует или была перемещена.',
                    'search_eyebrow'    => 'Результаты поиска',
                    'search_found'      => 'Найдено результатов: %d',
                    'search_empty'      => 'По вашему запросу ничего не найдено.',
                    'search_suggestion' => 'Попробуйте другой запрос или воспользуйтесь ссылками ниже.',
                ],
                'uk' => [
                    '404_title'         => 'Сторінку не знайдено',
                    '404_text'          => 'Сторінка, яку ви шукаєте, не існує або була переміщена.',
                    'search_eyebrow'    => 'Результати пошуку',
                    'search_found'      => 'Знайдено результатів: %d',
                    'search_empty'      => 'За вашим запитом нічого не знайдено.',
                    'search_suggestion' => 'Спробуйте інший запит або скористайтеся посиланнями нижче.',
                ],
                'es' => [
                    '404_title'         => 'Página no encontrada',
                    '404_text'          => 'La página que buscas no existe o ha sido movida.',
                    'search_eyebrow'    => 'Resultados de búsqueda',
                    'search_found'      => 'Se encontraron %d resultados',
                    'search_empty'      => 'No se encontraron resultados para tu búsqueda.',
                    'search_suggestion' => 'Prueba con otro término de búsqueda o explora los enlaces a continuación.',
                ],
            ],
        ],
    ];
}
