<?php

/**
 * Customizer string configuration — single source of truth for all theme text.
 */
function developer_theme_customizer_config()
{
    $year = gmdate('Y');

    return [
        'shared' => [
            'name'              => 'Your Name',
            'job_title'         => 'Senior Full-Stack Engineer',
            'email'             => 'your@email.com',
            'linkedin_url'      => 'https://www.linkedin.com/in/yourprofile/',
            'linkedin_display'  => 'linkedin.com/in/yourprofile',
            'github_url'        => 'https://github.com/yourusername',
            'github_display'    => 'github.com/yourusername',
            'telegram_url'      => 'https://t.me/yourusername',
            'telegram_display'  => '@yourusername',
            'location'          => 'Your City, Country',
            'cv_pdf_url'        => '/app/uploads/cv.pdf',
            'profile_image_url' => '/app/uploads/profile.jpg',
            'og_image_url'      => '/app/uploads/og-image.jpg',
            'map_embed_url'     => 'https://www.openstreetmap.org/export/embed.html?bbox=-0.2%2C51.4%2C0.1%2C51.6&layer=mapnik&marker=51.5%2C-0.1',
        ],
        'nav' => [
            'en' => [
                'brand'       => 'Your Name',
                'home'        => 'Home',
                'services'    => 'Services',
                'articles'    => 'Articles',
                'portfolio'   => 'Work',
                'contact'     => 'Contact',
                'footer_text' => 'WordPress & Laravel engineer. Technical audits, custom development, and rescue projects for businesses worldwide.',
                'footer_copy' => '&copy; ' . $year . ' Your Name. All rights reserved.',
            ],
            'ru' => [
                'brand'       => 'Ваше Имя',
                'home'        => 'Главная',
                'articles'    => 'Статьи',
                'portfolio'   => 'Портфолио',
                'contact'     => 'Контакты',
                'footer_text' => 'Senior Full-Stack Engineer. Мультиязычное портфолио, кейсы и технические статьи.',
                'footer_copy' => '&copy; ' . $year . ' Your Name. Все права защищены.',
            ],
            'uk' => [
                'brand'       => 'Ваше Ім'я',
                'home'        => 'Головна',
                'articles'    => 'Статті',
                'portfolio'   => 'Портфоліо',
                'contact'     => 'Контакти',
                'footer_text' => 'Senior Full-Stack Engineer. Мультимовне портфоліо, кейси та технічні статті.',
                'footer_copy' => '&copy; ' . $year . ' Your Name. Усі права захищені.',
            ],
            'es' => [
                'brand'       => 'Your Name',
                'home'        => 'Inicio',
                'articles'    => 'Artículos',
                'portfolio'   => 'Portafolio',
                'contact'     => 'Contacto',
                'footer_text' => 'Senior Full-Stack Engineer. Portafolio multilingüe, casos prácticos y artículos técnicos.',
                'footer_copy' => '&copy; ' . $year . ' Your Name. Todos los derechos reservados.',
            ],
        ],
        'templates' => [
            'front' => [
                'en' => [
                    'hero_eyebrow'     => 'Your Name &middot; WordPress & Laravel Engineer',
                    'hero_h1'          => 'I help businesses build, audit, and rescue WordPress & Laravel systems.',
                    'hero_lead'        => 'Custom development, technical audits, performance optimization, and long-term support for SaaS teams, agencies, and growing businesses.',
                    'hero_summary'     => '10+ years shipping production systems. Available for freelance, contract, and partnership work.',
                    'cta_book'         => 'Book a free call',
                    'cta_services'     => 'View services',
                    'cta_project'      => 'Discuss a project',
                    'cta_portfolio'    => 'View portfolio',
                    'cta_cv'           => 'Download CV',
                    'stat1_num'        => '10+ years',
                    'stat1_label'      => 'shipping production web systems',
                    'stat2_num'        => '50+',
                    'stat2_label'      => 'projects delivered for clients worldwide',
                    'stat3_num'        => 'Full-stack',
                    'stat3_label'      => 'backend, frontend, DevOps, and architecture',
                    'focus_label'      => 'Available for hire',
                    'focus_text'       => 'Taking on new projects: audits, custom plugins, migrations, and technical partnerships.',

                    'problems_eye'     => 'Common challenges',
                    'problems_h2'      => 'Sound familiar?',
                    'problems_intro'   => 'These are the problems my clients come to me with. If any of them resonate, I can help.',
                    'problem1_h3'      => 'Your WordPress site is slow or unreliable',
                    'problem1_p'       => 'Pages take too long to load, plugins conflict, hosting is maxed out. You need someone to diagnose the root cause and fix it properly.',
                    'problem2_h3'      => 'You need a custom plugin or feature',
                    'problem2_p'       => 'Off-the-shelf plugins don\'t fit your workflow. You need custom functionality built to spec — WooCommerce, integrations, or internal tools.',
                    'problem3_h3'      => 'Your codebase is fragile or hard to maintain',
                    'problem3_p'       => 'Legacy code, no tests, painful deployments. You need a senior developer to stabilize the system and make it safe to iterate on.',
                    'expertise_eye'    => 'Expertise',
                    'expertise_h2'     => 'What I do',
                    'expertise_intro'  => 'I work best in products that need more than isolated coding tasks: backend decisions, frontend implementation, delivery reliability, and measurable business outcomes.',
                    'exp_back_tag'     => 'Backend',
                    'exp_back_h3'      => 'Laravel systems that stay maintainable under growth.',
                    'exp_back_p'       => 'Service boundaries, queues, caching, billing workflows, clean integrations, and predictable code paths for real production use.',
                    'exp_front_tag'    => 'Frontend',
                    'exp_front_h3'     => 'Practical interfaces for dashboards and internal tools.',
                    'exp_front_p'      => 'React, Vue.js, and TypeScript implementations focused on clarity, performance, and the workflows teams actually need every day.',
                    'exp_perf_tag'     => 'Performance',
                    'exp_perf_h3'      => 'Optimization that improves real user experience.',
                    'exp_perf_p'       => 'Query tuning, database indexing, Redis, background jobs, and infrastructure decisions that remove bottlenecks instead of hiding them.',
                    'exp_del_tag'      => 'Delivery',
                    'exp_del_h3'       => 'Safer releases and better engineering flow.',
                    'exp_del_p'        => 'Docker, AWS, CI/CD, code reviews, and engineering discipline that reduce manual overhead and make teams more confident in production.',
                    'impact_eye'       => 'Impact',
                    'impact_h2'        => 'Selected results',
                    'impact_intro'     => 'The strongest work is usually operationally boring after launch: simpler releases, fewer incidents, better performance, and cleaner systems for the next iteration.',
                    'impact_items'     => [
                        'Modernized deployments by moving manual release routines into automated CI/CD pipelines, cutting release time from hours to minutes.',
                        'Improved production responsiveness through query optimization, database indexing, and Redis caching — reducing page load times by up to 60% on key user flows.',
                        'Built subscription billing and payment workflows with Laravel Cashier and Stripe, handling recurring charges, trials, and lifecycle events.',
                        'Helped raise engineering quality through reviews, mentoring, and stronger code ownership across distributed teams.',
                        'Delivered multilingual content platforms serving 100K+ monthly visitors with clean structure and SEO-aware architecture.',
                    ],
                    'experience_eye'   => 'Experience',
                    'experience_h2'    => 'Engineering background',
                    'experience_intro' => 'My strongest work sits at the intersection of product thinking and implementation: legacy modernization, architecture cleanup, delivery improvement, and shipping features that support real business goals.',
                    'role1_tag'        => '2020 — Present',
                    'role1_h3'         => 'Senior Full-Stack Engineer at Your Company',
                    'role1_p'          => 'Working across SaaS product engineering, frontend delivery, backend systems, content surfaces, and maintainable implementation for a mature writing-assistance platform used by enterprise customers worldwide.',
                    'role2_tag'        => '2016 — 2020',
                    'role2_h3'         => 'Full-Stack Developer across product and agency environments',
                    'role2_p'          => 'Building Laravel systems, WordPress platforms, APIs, billing logic, custom plugins, and business-facing tools across different product stages and client requirements.',
                    'role3_tag'        => '2014 — 2016',
                    'role3_h3'         => 'Web Developer — early career and freelance projects',
                    'role3_p'          => 'Learning the craft through real client work: custom WordPress themes, PHP backends, responsive layouts, and the habits that come from shipping under constraints.',
                    'stack_eye'        => 'Stack',
                    'stack_h2'         => 'Core technologies',
                    'stack_intro'      => 'I prefer straightforward tools and clear architecture over fashionable complexity. The stack should help the product move faster, not become the product.',
                    'stack_items'      => [ 'Laravel', 'PHP', 'React', 'Vue.js', 'TypeScript', 'JavaScript', 'MySQL', 'PostgreSQL', 'Redis', 'Docker', 'AWS', 'GitHub Actions', 'REST APIs', 'Stripe', 'WordPress', 'PHPUnit', 'Jest', 'Node.js' ],
                    'approach_eye'     => 'Approach',
                    'approach_h2'      => 'How I work',
                    'approach_intro'   => 'I care about the outcome, not just the output. Simple solutions that scale well, clear communication, and engineering decisions that stay maintainable over time.',
                    'approach_items'   => [
                        'Comfortable working independently and in distributed teams',
                        'Strong ownership from architecture to production deployment',
                        'Pragmatic about trade-offs — ship, learn, iterate',
                        'Clear technical communication with both engineers and stakeholders',
                        'Continuous improvement without chasing hype',
                    ],
                    'portfolio_eye'    => 'Portfolio',
                    'portfolio_h2'     => 'Selected product and platform work',
                    'portfolio_intro'  => 'These cases show the kind of work I do best: product-facing engineering, structured content experiences, and implementation that stays maintainable after launch.',
                    'services_eye'     => 'Services',
                    'services_h2'     => 'How I can help',
                    'services_intro'  => 'Fixed-scope packages with clear deliverables, timelines, and pricing. No surprises.',
                    'svc1_tag'        => 'Starting at $500',
                    'svc1_h3'         => 'WordPress Technical Audit',
                    'svc1_p'          => 'Full performance, security, and architecture review of your WordPress site. You get a detailed report with prioritized fixes and a roadmap.',
                    'svc1_cta'        => 'Learn more',
                    'svc2_tag'        => 'Starting at $2,000',
                    'svc2_h3'         => 'Custom Plugin Development',
                    'svc2_p'          => 'Purpose-built WordPress or WooCommerce plugins tailored to your business logic. Clean code, admin UI, documentation included.',
                    'svc2_cta'        => 'Learn more',
                    'svc3_tag'        => 'Starting at $1,500',
                    'svc3_h3'         => 'Rescue & Migration Projects',
                    'svc3_p'          => 'Broken site? Legacy mess? I stabilize, migrate, or rebuild your WordPress or Laravel project so it runs reliably again.',
                    'svc3_cta'        => 'Learn more',

                    'process_eye'     => 'Process',
                    'process_h2'      => 'How I work with clients',
                    'process_intro'   => 'Simple, transparent process from first call to delivery. No lengthy proposals or committee meetings.',
                    'step1_num'       => '01',
                    'step1_h3'        => 'Discovery call',
                    'step1_p'         => 'Free 15-minute call to understand your project, constraints, and goals. No obligation.',
                    'step2_num'       => '02',
                    'step2_h3'        => 'Proposal & scope',
                    'step2_p'         => 'Clear scope document with deliverables, timeline, and fixed price. You know exactly what you\'re getting.',
                    'step3_num'       => '03',
                    'step3_h3'        => 'Build & deliver',
                    'step3_p'         => 'I do the work, keep you updated, and deliver on time. You get the code, documentation, and support.',
                    'proof_eye'       => 'Trusted by',
                    'proof_names'     => [ 'Client A', 'Client B', 'Client C', 'Client D', 'Client E' ],
                    'writing_eye'      => 'Writing',
                    'writing_h2'       => 'Articles based on real project work',
                    'writing_intro'    => 'I write about Laravel, architecture, performance, and practical engineering topics. These are notes from real project work — not abstract theory.',
                    'contact_eye'      => 'Get started',
                    'contact_h2'       => 'Ready to fix or build your project?',
                    'contact_intro'    => 'Book a free 15-minute call to discuss your project — or send me a message with the details. I typically respond within 24 hours.',
                    'contact_cta'      => 'Send a message',
                    'contact_cta_book' => 'Book a free call',
                ],
                'ru' => [
                    'hero_eyebrow'     => 'Ваше Имя &middot; Senior Full-Stack Engineer',
                    'hero_h1'          => 'Проектирую масштабируемые веб-продукты с надёжной серверной архитектурой.',
                    'hero_lead'        => 'Разрабатываю и запускаю надёжные SaaS-системы, внутренние инструменты и продуктовые фичи на Laravel, React, Vue.js, TypeScript, MySQL, AWS, Docker и CI/CD.',
                    'hero_summary'     => 'Более 10 лет практического опыта. Помогаю командам модернизировать legacy-код, повышать производительность и выпускать поддерживаемое ПО без потери продуктового темпа.',
                    'cta_project'      => 'Обсудить проект',
                    'cta_portfolio'    => 'Портфолио',
                    'cta_cv'           => 'Скачать CV',
                    'stat1_num'        => '10+ лет',
                    'stat1_label'      => 'разработка production-систем',
                    'stat2_num'        => 'Full-stack',
                    'stat2_label'      => 'backend, frontend и ответственность за доставку',
                    'stat3_num'        => 'SaaS фокус',
                    'stat3_label'      => 'масштабируемые приложения, биллинг, производительность',
                    'focus_label'      => 'Текущий фокус',
                    'focus_text'       => 'Архитектура Laravel, продуктовая инженерия, масштабируемые интеграции и практичные процессы доставки.',
                    'expertise_eye'    => 'Экспертиза',
                    'expertise_h2'     => 'Что я делаю',
                    'expertise_intro'  => 'Лучше всего работаю в продуктах, где нужно больше, чем изолированные задачи: архитектурные решения, frontend-реализация, надёжная доставка и измеримые бизнес-результаты.',
                    'exp_back_tag'     => 'Backend',
                    'exp_back_h3'      => 'Laravel-системы, которые остаются поддерживаемыми при росте.',
                    'exp_back_p'       => 'Границы сервисов, очереди, кеширование, биллинг, чистые интеграции и предсказуемые пути кода для реального production-использования.',
                    'exp_front_tag'    => 'Frontend',
                    'exp_front_h3'     => 'Практичные интерфейсы для дашбордов и внутренних инструментов.',
                    'exp_front_p'      => 'React, Vue.js и TypeScript — реализации с фокусом на ясность, производительность и те рабочие процессы, которые команда использует каждый день.',
                    'exp_perf_tag'     => 'Производительность',
                    'exp_perf_h3'      => 'Оптимизация, которая улучшает реальный пользовательский опыт.',
                    'exp_perf_p'       => 'Тюнинг запросов, индексация БД, Redis, фоновые задачи и инфраструктурные решения, которые устраняют узкие места, а не прячут их.',
                    'exp_del_tag'      => 'Доставка',
                    'exp_del_h3'       => 'Безопасные релизы и лучший инженерный процесс.',
                    'exp_del_p'        => 'Docker, AWS, CI/CD, код-ревью и инженерная дисциплина, которые снижают ручной overhead и повышают уверенность команды в production.',
                    'impact_eye'       => 'Результаты',
                    'impact_h2'        => 'Избранные достижения',
                    'impact_intro'     => 'Лучшая работа после запуска обычно выглядит скучно: простые релизы, меньше инцидентов, лучшая производительность и чистые системы для следующей итерации.',
                    'impact_items'     => [
                        'Модернизировал деплой: перевёл ручные релизы в автоматические CI/CD-пайплайны, сократив время релиза с часов до минут.',
                        'Улучшил отзывчивость production через оптимизацию запросов, индексацию БД и Redis-кеширование — снижение времени загрузки до 60% на ключевых сценариях.',
                        'Построил подписочный биллинг и платёжные потоки с Laravel Cashier и Stripe: рекуррентные платежи, триалы и lifecycle-события.',
                        'Повысил качество инженерии через ревью, менторство и укрепление ownership-культуры в распределённых командах.',
                        'Доставил мультиязычные контент-платформы с 100K+ посетителей в месяц, чистой структурой и SEO-ориентированной архитектурой.',
                    ],
                    'experience_eye'   => 'Опыт',
                    'experience_h2'    => 'Инженерный бекграунд',
                    'experience_intro' => 'Моя сильнейшая работа на пересечении продуктового мышления и реализации: модернизация legacy, очистка архитектуры, улучшение доставки и фичи, поддерживающие реальные бизнес-цели.',
                    'role1_tag'        => '2020 — настоящее время',
                    'role1_h3'         => 'Senior Full-Stack Engineer в Your Company',
                    'role1_p'          => 'SaaS-инженерия, frontend-доставка, backend-системы, контентные поверхности и поддерживаемая реализация для зрелой платформы проверки правописания, используемой корпоративными клиентами по всему миру.',
                    'role2_tag'        => '2016 — 2020',
                    'role2_h3'         => 'Full-Stack разработчик в продуктовых и агентских средах',
                    'role2_p'          => 'Laravel-системы, WordPress-платформы, API, биллинг, кастомные плагины и бизнес-инструменты на разных стадиях продуктов и клиентских проектов.',
                    'role3_tag'        => '2014 — 2016',
                    'role3_h3'         => 'Web-разработчик — начало карьеры и фриланс',
                    'role3_p'          => 'Освоение ремесла через реальную клиентскую работу: кастомные WordPress-темы, PHP-бекенды, адаптивная вёрстка и привычки, которые формируются при регулярных поставках.',
                    'stack_eye'        => 'Стек',
                    'stack_h2'         => 'Основные технологии',
                    'stack_intro'      => 'Предпочитаю простые инструменты и ясную архитектуру, а не модную сложность. Стек должен помогать продукту двигаться быстрее, а не становиться продуктом.',
                    'stack_items'      => [ 'Laravel', 'PHP', 'React', 'Vue.js', 'TypeScript', 'JavaScript', 'MySQL', 'PostgreSQL', 'Redis', 'Docker', 'AWS', 'GitHub Actions', 'REST APIs', 'Stripe', 'WordPress', 'PHPUnit', 'Jest', 'Node.js' ],
                    'approach_eye'     => 'Подход',
                    'approach_h2'      => 'Как я работаю',
                    'approach_intro'   => 'Мне важен результат, а не только объём работы. Простые решения, которые масштабируются, ясная коммуникация и инженерные решения, которые остаются поддерживаемыми со временем.',
                    'approach_items'   => [
                        'Комфортно работаю самостоятельно и в распределённых командах',
                        'Сильный ownership от архитектуры до production-деплоя',
                        'Прагматичный подход к компромиссам — доставить, изучить, итерировать',
                        'Чёткая техническая коммуникация и с инженерами, и со стейкхолдерами',
                        'Постоянное улучшение без погони за хайпом',
                    ],
                    'portfolio_eye'    => 'Портфолио',
                    'portfolio_h2'     => 'Избранные продуктовые и платформенные работы',
                    'portfolio_intro'  => 'Эти кейсы показывают мою сильнейшую работу: продуктовая инженерия, структурированный контент и реализация, которая остаётся поддерживаемой после запуска.',
                    'services_eye'     => 'Услуги',
                    'services_h2'     => 'Чем могу помочь',
                    'services_intro'  => 'Доступен для фриланса, контрактной и удалённой продуктовой работы. Вот где я приношу максимум пользы.',
                    'svc1_tag'        => 'SaaS и продукты',
                    'svc1_h3'         => 'SaaS и продуктовая инженерия',
                    'svc1_p'          => 'Laravel API, биллинг и подписки, сторонние интеграции, архитектура платформ и масштабируемые backend-системы для растущих продуктов.',
                    'svc2_tag'        => 'WordPress',
                    'svc2_h3'         => 'Кастомный WordPress и плагины',
                    'svc2_p'          => 'Кастомные темы, экосистемы плагинов, мультиязычные платформы, WooCommerce и контент-архитектура, с которой редакторам приятно работать.',
                    'svc3_tag'        => 'Производительность',
                    'svc3_h3'         => 'Производительность и архитектура',
                    'svc3_p'          => 'Миграции платформ, перестройка legacy, оптимизация запросов, стратегия кеширования и очистка инфраструктуры для следующей итерации.',
                    'svc4_tag'        => 'DevOps',
                    'svc4_h3'         => 'Доставка и CI/CD',
                    'svc4_p'          => 'Docker-окружения, GitHub Actions, автоматические деплои, ответственность за релизы и инженерная дисциплина для уверенности в production.',
                    'proof_eye'       => 'Работал с',
                    'proof_names'     => [ 'Client A', 'Client B', 'Client C', 'Client D', 'Client E' ],
                    'writing_eye'      => 'Статьи',
                    'writing_h2'       => 'Статьи на основе реальных проектов',
                    'writing_intro'    => 'Пишу о Laravel, архитектуре, производительности и практической инженерии. Это заметки из реальных проектов — не абстрактная теория.',
                    'contact_eye'      => 'Контакты',
                    'contact_h2'       => 'Нужна помощь с продуктом или перестройкой платформы?',
                    'contact_intro'    => 'Если вы улучшаете существующую систему, запускаете что-то новое или ищете senior-инженера, который может работать через backend, frontend и инфраструктуру — напишите.',
                    'contact_cta'      => 'Написать сообщение',
                ],
                'uk' => [
                    'hero_eyebrow'     => 'Ваше Ім'я &middot; Senior Full-Stack Engineer',
                    'hero_h1'          => 'Проєктую масштабовані веб-продукти з надійною серверною архітектурою.',
                    'hero_lead'        => 'Розробляю та запускаю надійні SaaS-системи, внутрішні інструменти та продуктові фічі на Laravel, React, Vue.js, TypeScript, MySQL, AWS, Docker та CI/CD.',
                    'hero_summary'     => 'Понад 10 років практичного досвіду. Допомагаю командам модернізувати legacy-код, підвищувати продуктивність і випускати підтримуване ПЗ без втрати продуктового темпу.',
                    'cta_project'      => 'Обговорити проєкт',
                    'cta_portfolio'    => 'Портфоліо',
                    'cta_cv'           => 'Завантажити CV',
                    'stat1_num'        => '10+ років',
                    'stat1_label'      => 'розробка production-систем',
                    'stat2_num'        => 'Full-stack',
                    'stat2_label'      => 'backend, frontend та відповідальність за доставку',
                    'stat3_num'        => 'SaaS фокус',
                    'stat3_label'      => 'масштабовані застосунки, білінг, продуктивність',
                    'focus_label'      => 'Поточний фокус',
                    'focus_text'       => 'Архітектура Laravel, продуктова інженерія, масштабовані інтеграції та практичні процеси доставки.',
                    'expertise_eye'    => 'Експертиза',
                    'expertise_h2'     => 'Що я роблю',
                    'expertise_intro'  => 'Найкраще працюю в продуктах, де потрібно більше, ніж ізольовані задачі: архітектурні рішення, frontend-реалізація, надійна доставка та вимірювані бізнес-результати.',
                    'exp_back_tag'     => 'Backend',
                    'exp_back_h3'      => 'Laravel-системи, що залишаються підтримуваними при зростанні.',
                    'exp_back_p'       => 'Межі сервісів, черги, кешування, білінг, чисті інтеграції та передбачувані шляхи коду для реального production-використання.',
                    'exp_front_tag'    => 'Frontend',
                    'exp_front_h3'     => 'Практичні інтерфейси для дашбордів та внутрішніх інструментів.',
                    'exp_front_p'      => 'React, Vue.js та TypeScript — реалізації з фокусом на ясність, продуктивність і ті робочі процеси, які команда використовує щодня.',
                    'exp_perf_tag'     => 'Продуктивність',
                    'exp_perf_h3'      => 'Оптимізація, що покращує реальний користувацький досвід.',
                    'exp_perf_p'       => 'Тюнінг запитів, індексація БД, Redis, фонові задачі та інфраструктурні рішення, що усувають вузькі місця, а не ховають їх.',
                    'exp_del_tag'      => 'Доставка',
                    'exp_del_h3'       => 'Безпечні релізи та кращий інженерний процес.',
                    'exp_del_p'        => 'Docker, AWS, CI/CD, код-рев\'ю та інженерна дисципліна, що знижують ручний overhead і підвищують впевненість команди в production.',
                    'impact_eye'       => 'Результати',
                    'impact_h2'        => 'Обрані досягнення',
                    'impact_intro'     => 'Найкраща робота після запуску зазвичай виглядає нудно: прості релізи, менше інцидентів, краща продуктивність і чисті системи для наступної ітерації.',
                    'impact_items'     => [
                        'Модернізував деплой: перевів ручні релізи в автоматичні CI/CD-пайплайни, скоротивши час релізу з годин до хвилин.',
                        'Покращив відгук production через оптимізацію запитів, індексацію БД та Redis-кешування — зниження часу завантаження до 60% на ключових сценаріях.',
                        'Побудував підписковий білінг та платіжні потоки з Laravel Cashier і Stripe: рекурентні платежі, тріали та lifecycle-події.',
                        'Підвищив якість інженерії через рев\'ю, менторство та зміцнення ownership-культури в розподілених командах.',
                        'Доставив мультимовні контент-платформи з 100K+ відвідувачів на місяць, чистою структурою та SEO-орієнтованою архітектурою.',
                    ],
                    'experience_eye'   => 'Досвід',
                    'experience_h2'    => 'Інженерний бекграунд',
                    'experience_intro' => 'Моя найсильніша робота на перетині продуктового мислення та реалізації: модернізація legacy, очищення архітектури, покращення доставки та фічі, що підтримують реальні бізнес-цілі.',
                    'role1_tag'        => '2020 — теперішній час',
                    'role1_h3'         => 'Senior Full-Stack Engineer у Your Company',
                    'role1_p'          => 'SaaS-інженерія, frontend-доставка, backend-системи, контентні поверхні та підтримувана реалізація для зрілої платформи перевірки правопису, яку використовують корпоративні клієнти по всьому світу.',
                    'role2_tag'        => '2016 — 2020',
                    'role2_h3'         => 'Full-Stack розробник у продуктових та агентських середовищах',
                    'role2_p'          => 'Laravel-системи, WordPress-платформи, API, білінг, кастомні плагіни та бізнес-інструменти на різних стадіях продуктів та клієнтських проєктів.',
                    'role3_tag'        => '2014 — 2016',
                    'role3_h3'         => 'Web-розробник — початок кар\'єри та фріланс',
                    'role3_p'          => 'Освоєння ремесла через реальну клієнтську роботу: кастомні WordPress-теми, PHP-бекенди, адаптивна верстка та звички, що формуються при регулярних поставках.',
                    'stack_eye'        => 'Стек',
                    'stack_h2'         => 'Основні технології',
                    'stack_intro'      => 'Надаю перевагу простим інструментам і ясній архітектурі, а не модній складності. Стек повинен допомагати продукту рухатися швидше, а не ставати продуктом.',
                    'stack_items'      => [ 'Laravel', 'PHP', 'React', 'Vue.js', 'TypeScript', 'JavaScript', 'MySQL', 'PostgreSQL', 'Redis', 'Docker', 'AWS', 'GitHub Actions', 'REST APIs', 'Stripe', 'WordPress', 'PHPUnit', 'Jest', 'Node.js' ],
                    'approach_eye'     => 'Підхід',
                    'approach_h2'      => 'Як я працюю',
                    'approach_intro'   => 'Мені важливий результат, а не лише обсяг роботи. Прості рішення, що масштабуються, ясна комунікація та інженерні рішення, що залишаються підтримуваними з часом.',
                    'approach_items'   => [
                        'Комфортно працюю самостійно і в розподілених командах',
                        'Сильний ownership від архітектури до production-деплою',
                        'Прагматичний підхід до компромісів — доставити, вивчити, ітерувати',
                        'Чітка технічна комунікація і з інженерами, і зі стейкхолдерами',
                        'Постійне покращення без гонитви за хайпом',
                    ],
                    'portfolio_eye'    => 'Портфоліо',
                    'portfolio_h2'     => 'Обрані продуктові та платформні роботи',
                    'portfolio_intro'  => 'Ці кейси показують мою найсильнішу роботу: продуктова інженерія, структурований контент та реалізація, що залишається підтримуваною після запуску.',
                    'services_eye'     => 'Послуги',
                    'services_h2'     => 'Чим можу допомогти',
                    'services_intro'  => 'Доступний для фрілансу, контрактної та віддаленої продуктової роботи. Ось де я приношу найбільше користі.',
                    'svc1_tag'        => 'SaaS і продукти',
                    'svc1_h3'         => 'SaaS та продуктова інженерія',
                    'svc1_p'          => 'Laravel API, білінг і підписки, сторонні інтеграції, архітектура платформ та масштабовані backend-системи для зростаючих продуктів.',
                    'svc2_tag'        => 'WordPress',
                    'svc2_h3'         => 'Кастомний WordPress та плагіни',
                    'svc2_p'          => 'Кастомні теми, екосистеми плагінів, мультимовні платформи, WooCommerce та контент-архітектура, з якою редакторам зручно працювати.',
                    'svc3_tag'        => 'Продуктивність',
                    'svc3_h3'         => 'Продуктивність та архітектура',
                    'svc3_p'          => 'Міграції платформ, перебудова legacy, оптимізація запитів, стратегія кешування та очищення інфраструктури для наступної ітерації.',
                    'svc4_tag'        => 'DevOps',
                    'svc4_h3'         => 'Доставка та CI/CD',
                    'svc4_p'          => 'Docker-оточення, GitHub Actions, автоматичні деплої, відповідальність за релізи та інженерна дисципліна для впевненості в production.',
                    'proof_eye'       => 'Працював з',
                    'proof_names'     => [ 'Client A', 'Client B', 'Client C', 'Client D', 'Client E' ],
                    'writing_eye'      => 'Статті',
                    'writing_h2'       => 'Статті на основі реальних проєктів',
                    'writing_intro'    => 'Пишу про Laravel, архітектуру, продуктивність та практичну інженерію. Це нотатки з реальних проєктів — не абстрактна теорія.',
                    'contact_eye'      => 'Контакти',
                    'contact_h2'       => 'Потрібна допомога з продуктом або перебудовою платформи?',
                    'contact_intro'    => 'Якщо ви покращуєте існуючу систему, запускаєте щось нове або шукаєте senior-інженера, що може працювати через backend, frontend та інфраструктуру — напишіть.',
                    'contact_cta'      => 'Написати повідомлення',
                ],
                'es' => [
                    'hero_eyebrow'     => 'Your Name &middot; Senior Full-Stack Engineer',
                    'hero_h1'          => 'Construyendo productos web escalables con arquitectura backend sólida.',
                    'hero_lead'        => 'Diseño y entrego sistemas SaaS confiables, herramientas internas y funcionalidades de producto con Laravel, React, Vue.js, TypeScript, MySQL, AWS, Docker y CI/CD.',
                    'hero_summary'     => 'Con más de 10 años de experiencia práctica, ayudo a equipos a modernizar código heredado, mejorar el rendimiento en producción y entregar software mantenible sin perder impulso de producto.',
                    'cta_project'      => 'Hablemos de tu proyecto',
                    'cta_portfolio'    => 'Ver portafolio',
                    'cta_cv'           => 'Descargar CV',
                    'stat1_num'        => '10+ años',
                    'stat1_label'      => 'entregando sistemas web en producción',
                    'stat2_num'        => 'Full-stack',
                    'stat2_label'      => 'backend, frontend y ownership de entrega',
                    'stat3_num'        => 'Enfoque SaaS',
                    'stat3_label'      => 'apps escalables, facturación, rendimiento',
                    'focus_label'      => 'Enfoque actual',
                    'focus_text'       => 'Arquitectura Laravel, ingeniería de producto, integraciones escalables y flujos de entrega prácticos.',
                    'expertise_eye'    => 'Experiencia',
                    'expertise_h2'     => 'Qué hago',
                    'expertise_intro'  => 'Trabajo mejor en productos que necesitan más que tareas aisladas: decisiones de backend, implementación frontend, entrega confiable y resultados de negocio medibles.',
                    'exp_back_tag'     => 'Backend',
                    'exp_back_h3'      => 'Sistemas Laravel que se mantienen escalables.',
                    'exp_back_p'       => 'Límites de servicio, colas, caché, flujos de facturación, integraciones limpias y rutas de código predecibles para uso real en producción.',
                    'exp_front_tag'    => 'Frontend',
                    'exp_front_h3'     => 'Interfaces prácticas para dashboards y herramientas internas.',
                    'exp_front_p'      => 'Implementaciones con React, Vue.js y TypeScript enfocadas en claridad, rendimiento y los flujos que los equipos necesitan cada día.',
                    'exp_perf_tag'     => 'Rendimiento',
                    'exp_perf_h3'      => 'Optimización que mejora la experiencia real del usuario.',
                    'exp_perf_p'       => 'Ajuste de consultas, indexación de BD, Redis, tareas en segundo plano y decisiones de infraestructura que eliminan cuellos de botella en vez de ocultarlos.',
                    'exp_del_tag'      => 'Entrega',
                    'exp_del_h3'       => 'Releases más seguros y mejor flujo de ingeniería.',
                    'exp_del_p'        => 'Docker, AWS, CI/CD, code reviews y disciplina de ingeniería que reducen el overhead manual y dan más confianza al equipo en producción.',
                    'impact_eye'       => 'Impacto',
                    'impact_h2'        => 'Resultados seleccionados',
                    'impact_intro'     => 'El mejor trabajo después del lanzamiento suele parecer aburrido: releases simples, menos incidentes, mejor rendimiento y sistemas más limpios para la siguiente iteración.',
                    'impact_items'     => [
                        'Modernización del deploy: migré releases manuales a pipelines CI/CD automatizados, reduciendo el tiempo de release de horas a minutos.',
                        'Mejoré la capacidad de respuesta en producción mediante optimización de consultas, indexación y caché Redis — reduciendo tiempos de carga hasta un 60% en flujos clave.',
                        'Construí facturación por suscripción con Laravel Cashier y Stripe: cobros recurrentes, pruebas y eventos de ciclo de vida.',
                        'Elevé la calidad de ingeniería a través de reviews, mentoría y cultura de ownership más fuerte en equipos distribuidos.',
                        'Entregué plataformas de contenido multilingüe con más de 100K visitantes mensuales, estructura limpia y arquitectura orientada a SEO.',
                    ],
                    'experience_eye'   => 'Experiencia',
                    'experience_h2'    => 'Trayectoria de ingeniería',
                    'experience_intro' => 'Mi trabajo más fuerte está en la intersección del pensamiento de producto y la implementación: modernización legacy, limpieza de arquitectura, mejora de entrega y features que apoyan objetivos de negocio reales.',
                    'role1_tag'        => '2020 — Presente',
                    'role1_h3'         => 'Senior Full-Stack Engineer en Your Company',
                    'role1_p'          => 'Ingeniería de producto SaaS, entrega frontend, sistemas backend, superficies de contenido e implementación mantenible para una plataforma madura de asistencia de escritura usada por clientes empresariales.',
                    'role2_tag'        => '2016 — 2020',
                    'role2_h3'         => 'Desarrollador Full-Stack en entornos de producto y agencia',
                    'role2_p'          => 'Sistemas Laravel, plataformas WordPress, APIs, facturación, plugins personalizados y herramientas de negocio en diferentes etapas de producto y proyectos de clientes.',
                    'role3_tag'        => '2014 — 2016',
                    'role3_h3'         => 'Desarrollador Web — inicio de carrera y freelance',
                    'role3_p'          => 'Aprendiendo el oficio a través de trabajo real con clientes: temas WordPress personalizados, backends PHP, layouts responsivos y los hábitos que se forman al entregar bajo restricciones.',
                    'stack_eye'        => 'Stack',
                    'stack_h2'         => 'Tecnologías principales',
                    'stack_intro'      => 'Prefiero herramientas directas y arquitectura clara sobre complejidad de moda. El stack debe ayudar al producto a moverse más rápido, no convertirse en el producto.',
                    'stack_items'      => [ 'Laravel', 'PHP', 'React', 'Vue.js', 'TypeScript', 'JavaScript', 'MySQL', 'PostgreSQL', 'Redis', 'Docker', 'AWS', 'GitHub Actions', 'REST APIs', 'Stripe', 'WordPress', 'PHPUnit', 'Jest', 'Node.js' ],
                    'approach_eye'     => 'Enfoque',
                    'approach_h2'      => 'Cómo trabajo',
                    'approach_intro'   => 'Me importa el resultado, no solo el volumen de trabajo. Soluciones simples que escalan bien, comunicación clara y decisiones de ingeniería que se mantienen con el tiempo.',
                    'approach_items'   => [
                        'Cómodo trabajando de forma independiente y en equipos distribuidos',
                        'Fuerte ownership desde la arquitectura hasta el deploy en producción',
                        'Pragmático con los trade-offs — entregar, aprender, iterar',
                        'Comunicación técnica clara tanto con ingenieros como con stakeholders',
                        'Mejora continua sin perseguir tendencias',
                    ],
                    'portfolio_eye'    => 'Portafolio',
                    'portfolio_h2'     => 'Trabajos seleccionados de producto y plataforma',
                    'portfolio_intro'  => 'Estos casos muestran mi mejor trabajo: ingeniería orientada a producto, experiencias de contenido estructurado e implementación que se mantiene después del lanzamiento.',
                    'services_eye'     => 'Servicios',
                    'services_h2'     => 'En qué puedo ayudarte',
                    'services_intro'  => 'Disponible para freelance, contrato y trabajo remoto de producto. Aquí es donde aporto más valor.',
                    'svc1_tag'        => 'SaaS y productos',
                    'svc1_h3'         => 'Ingeniería SaaS y de producto',
                    'svc1_p'          => 'APIs Laravel, facturación y suscripciones, integraciones externas, arquitectura de plataformas y sistemas backend escalables para productos en crecimiento.',
                    'svc2_tag'        => 'WordPress',
                    'svc2_h3'         => 'WordPress personalizado y plugins',
                    'svc2_p'          => 'Temas personalizados, ecosistemas de plugins, plataformas multilingües, WooCommerce y arquitectura de contenido que los editores disfrutan usar.',
                    'svc3_tag'        => 'Rendimiento',
                    'svc3_h3'         => 'Rendimiento y arquitectura',
                    'svc3_p'          => 'Migraciones de plataformas, reconstrucciones legacy, optimización de consultas, estrategia de caché y limpieza de infraestructura para la siguiente iteración.',
                    'svc4_tag'        => 'DevOps',
                    'svc4_h3'         => 'Entrega y CI/CD',
                    'svc4_p'          => 'Entornos Docker, GitHub Actions, deploys automatizados, ownership de releases y disciplina de ingeniería para confianza en producción.',
                    'proof_eye'       => 'He trabajado con',
                    'proof_names'     => [ 'Client A', 'Client B', 'Client C', 'Client D', 'Client E' ],
                    'writing_eye'      => 'Artículos',
                    'writing_h2'       => 'Artículos basados en trabajo real',
                    'writing_intro'    => 'Escribo sobre Laravel, arquitectura, rendimiento e ingeniería práctica. Son notas de proyectos reales — no teoría abstracta.',
                    'contact_eye'      => 'Contacto',
                    'contact_h2'       => '¿Necesitas ayuda con un producto o reconstrucción de plataforma?',
                    'contact_intro'    => 'Si estás mejorando un sistema existente, lanzando algo nuevo o buscas un ingeniero senior que pueda operar en backend, frontend e infraestructura — escríbeme.',
                    'contact_cta'      => 'Enviar un mensaje',
                ],
            ],
            'home' => [
                'en' => [
                    'page_title' => 'Articles',
                    'page_intro' => 'Notes on Laravel, architecture, performance, and practical software engineering. Based on real project work, written for engineers and teams who build products.',
                    'read_more'  => 'Read article',
                    'no_posts'   => 'No articles yet. Check back soon.',
                    'older'      => 'Older articles',
                    'newer'      => 'Newer articles',
                ],
                'ru' => [
                    'page_title' => 'Статьи',
                    'page_intro' => 'Заметки о Laravel, архитектуре, производительности и практической инженерии. Из реальных проектов, для разработчиков и команд.',
                    'read_more'  => 'Читать статью',
                    'no_posts'   => 'Статей пока нет. Заходите позже.',
                    'older'      => 'Старые статьи',
                    'newer'      => 'Новые статьи',
                ],
                'uk' => [
                    'page_title' => 'Статті',
                    'page_intro' => 'Нотатки про Laravel, архітектуру, продуктивність та практичну інженерію. З реальних проєктів, для розробників і команд.',
                    'read_more'  => 'Читати статтю',
                    'no_posts'   => 'Статей поки немає. Заходьте пізніше.',
                    'older'      => 'Старіші статті',
                    'newer'      => 'Новіші статті',
                ],
                'es' => [
                    'page_title' => 'Artículos',
                    'page_intro' => 'Notas sobre Laravel, arquitectura, rendimiento e ingeniería práctica. Basadas en proyectos reales, escritas para ingenieros y equipos.',
                    'read_more'  => 'Leer artículo',
                    'no_posts'   => 'Aún no hay artículos. Vuelve pronto.',
                    'older'      => 'Artículos anteriores',
                    'newer'      => 'Artículos más recientes',
                ],
            ],
            'archive_portfolio' => [
                'en' => [
                    'page_title' => 'Portfolio',
                    'page_intro' => 'Product-facing engineering, structured content experiences, and implementation that stays maintainable after launch.',
                    'no_posts'   => 'No portfolio items yet.',
                ],
                'ru' => [
                    'page_title' => 'Портфолио',
                    'page_intro' => 'Продуктовая инженерия, структурированный контент и реализация, которая остаётся поддерживаемой после запуска.',
                    'no_posts'   => 'Портфолио пока пусто.',
                ],
                'uk' => [
                    'page_title' => 'Портфоліо',
                    'page_intro' => 'Продуктова інженерія, структурований контент та реалізація, що залишається підтримуваною після запуску.',
                    'no_posts'   => 'Портфоліо поки порожнє.',
                ],
                'es' => [
                    'page_title' => 'Portafolio',
                    'page_intro' => 'Ingeniería orientada a producto, experiencias de contenido estructurado e implementación que se mantiene después del lanzamiento.',
                    'no_posts'   => 'Aún no hay elementos en el portafolio.',
                ],
            ],
            'contact' => [
                'en' => [
                    'page_title'   => 'Get in touch',
                    'page_intro'   => 'Whether you have a project in mind, need a senior engineer for your team, or just want to say hello — I am happy to hear from you.',
                    'form_heading' => 'Send a message',
                    'info_heading' => 'Contact details',
                    'location_lbl' => 'Location',
                    'location'     => 'Your City, Country',
                    'availability' => 'Available for remote work worldwide and on-site in the Valencia / Alicante region.',
                ],
                'ru' => [
                    'page_title'   => 'Свяжитесь со мной',
                    'page_intro'   => 'Если у вас есть проект, вам нужен опытный инженер в команду, или просто хотите написать — буду рад вашему сообщению.',
                    'form_heading' => 'Написать сообщение',
                    'info_heading' => 'Контактные данные',
                    'location_lbl' => 'Расположение',
                    'location'     => 'Коста Бланка, Испания',
                    'availability' => 'Доступен для удалённой работы по всему миру и на месте в регионе Валенсия / Аликанте.',
                ],
                'uk' => [
                    'page_title'   => 'Зв\'язатися зі мною',
                    'page_intro'   => 'Якщо у вас є проєкт, потрібен досвідчений інженер у команду, або просто хочете написати — буду радий вашому повідомленню.',
                    'form_heading' => 'Написати повідомлення',
                    'info_heading' => 'Контактні дані',
                    'location_lbl' => 'Розташування',
                    'location'     => 'Коста Бланка, Іспанія',
                    'availability' => 'Доступний для віддаленої роботи по всьому світу та на місці в регіоні Валенсія / Аліканте.',
                ],
                'es' => [
                    'page_title'   => 'Ponte en contacto',
                    'page_intro'   => 'Si tienes un proyecto en mente, necesitas un ingeniero senior para tu equipo, o simplemente quieres saludar — estaré encantado de escucharte.',
                    'form_heading' => 'Enviar un mensaje',
                    'info_heading' => 'Datos de contacto',
                    'location_lbl' => 'Ubicación',
                    'location'     => 'Tu Ciudad, País',
                    'availability' => 'Disponible para trabajo remoto a nivel mundial y presencial en la zona de Valencia / Alicante.',
                ],
            ],
            'about' => [
                'en' => [
                    'about_eye'        => 'About',
                    'about_h1'         => 'The person behind the code',
                    'about_intro'      => 'Senior Full-Stack Engineer with 10+ years of experience shipping production systems for SaaS products, content platforms, and growing businesses.',

                    'bio_h2'           => 'Who I am',
                    'bio_p1'           => 'I am Your Name, a senior full-stack engineer based in Your City, Country. I specialize in WordPress and Laravel systems — building custom plugins, auditing performance, rescuing broken projects, and architecting backends that scale.',
                    'bio_p2'           => 'Over the past decade, I have worked with SaaS companies, digital agencies, and growing businesses across Europe and beyond. I care about clean code, pragmatic architecture, and shipping work that stays maintainable long after the project ends.',

                    'exp_h2'           => 'Professional experience',
                    'exp_intro'        => 'My strongest work sits at the intersection of product thinking and implementation: legacy modernization, architecture cleanup, delivery improvement, and shipping features that support real business goals.',
                    'role1_date'       => '2020 — Present',
                    'role1_h3'         => 'Senior Full-Stack Engineer at Your Company',
                    'role1_p'          => 'Working across SaaS product engineering, frontend delivery, backend systems, content surfaces, and maintainable implementation for a mature writing-assistance platform used by enterprise customers worldwide.',
                    'role2_date'       => '2016 — 2020',
                    'role2_h3'         => 'Full-Stack Developer across product and agency environments',
                    'role2_p'          => 'Building Laravel systems, WordPress platforms, APIs, billing logic, custom plugins, and business-facing tools across different product stages and client requirements.',
                    'role3_date'       => '2014 — 2016',
                    'role3_h3'         => 'Web Developer — early career and freelance projects',
                    'role3_p'          => 'Learning the craft through real client work: custom WordPress themes, PHP backends, responsive layouts, and the habits that come from shipping under constraints.',

                    'stack_h2'         => 'Core technologies',
                    'stack_intro'      => 'I prefer straightforward tools and clear architecture over fashionable complexity. The stack should help the product move faster, not become the product.',
                    'about_stack_items' => ['Laravel', 'PHP', 'React', 'Vue.js', 'TypeScript', 'JavaScript', 'MySQL', 'PostgreSQL', 'Redis', 'Docker', 'AWS', 'GitHub Actions', 'REST APIs', 'Stripe', 'WordPress', 'PHPUnit', 'Jest', 'Node.js'],

                    'approach_h2'      => 'How I work',
                    'approach_intro'   => 'I care about the outcome, not just the output. Simple solutions that scale well, clear communication, and engineering decisions that stay maintainable over time.',
                    'approach_items'   => [
                        'Comfortable working independently and in distributed teams',
                        'Strong ownership from architecture to production deployment',
                        'Pragmatic about trade-offs — ship, learn, iterate',
                        'Clear technical communication with both engineers and stakeholders',
                        'Continuous improvement without chasing hype',
                    ],

                    'cta_h2'           => 'Want to work together?',
                    'cta_p'            => 'I am available for freelance projects, technical audits, and long-term partnerships. Let us talk about how I can help your business.',
                    'cta_book'         => 'Book a free call',
                    'cta_contact'      => 'Send a message',
                ],
            ],
            'single' => [
                'en' => [
                    'breadcrumbs'      => 'Breadcrumbs',
                    'post_nav'         => 'Post page navigation',
                    'blog_article'     => 'Blog article',
                    'published'        => 'Published',
                    'updated'          => 'Updated',
                    'reading_time'     => 'min read',
                    'toc'              => 'On this page',
                    'recent_posts'     => 'More articles',
                    'cta_eyebrow'      => 'Need a senior engineer?',
                    'cta_title'        => 'I help teams modernize products, improve performance, and ship cleaner platforms.',
                    'cta_body'         => 'From architecture and Laravel backends to frontend delivery, SEO-ready content, and developer workflows.',
                    'cta_primary'      => 'Start a conversation',
                    'cta_secondary'    => 'See selected work',
                    'author_title'     => 'About the author',
                    'author_body'      => 'Senior Full-Stack Engineer with 10+ years of experience building SaaS products, multilingual content platforms, and modern web applications.',
                    'share_title'      => 'Share this article',
                    'next_article'     => 'Next article',
                    'previous_article' => 'Previous article',
                    'explore_more'     => 'Explore more',
                    'footer_text'      => 'Multilingual portfolio, case studies, and technical writing.',
                ],
                'ru' => [
                    'breadcrumbs'      => 'Хлебные крошки',
                    'post_nav'         => 'Навигация по странице статьи',
                    'blog_article'     => 'Статья блога',
                    'published'        => 'Опубликовано',
                    'updated'          => 'Обновлено',
                    'reading_time'     => 'мин чтения',
                    'toc'              => 'Содержание',
                    'recent_posts'     => 'Другие статьи',
                    'cta_eyebrow'      => 'Нужен senior engineer?',
                    'cta_title'        => 'Помогаю командам модернизировать продукты, ускорять платформы и выпускать более качественные решения.',
                    'cta_body'         => 'От архитектуры и Laravel-бэкендов до фронтенда, SEO-подготовленного контента и инженерных процессов.',
                    'cta_primary'      => 'Связаться',
                    'cta_secondary'    => 'Смотреть кейсы',
                    'author_title'     => 'Об авторе',
                    'author_body'      => 'Senior Full-Stack Engineer с опытом более 10 лет в SaaS, мультиязычных контент-платформах и современных веб-продуктах.',
                    'share_title'      => 'Поделиться статьей',
                    'next_article'     => 'Следующая статья',
                    'previous_article' => 'Предыдущая статья',
                    'explore_more'     => 'Смотрите также',
                    'footer_text'      => 'Мультиязычное портфолио, кейсы и технические статьи.',
                ],
                'uk' => [
                    'breadcrumbs'      => 'Хлібні крихти',
                    'post_nav'         => 'Навігація сторінкою статті',
                    'blog_article'     => 'Стаття блогу',
                    'published'        => 'Опубліковано',
                    'updated'          => 'Оновлено',
                    'reading_time'     => 'хв читання',
                    'toc'              => 'Зміст',
                    'recent_posts'     => 'Інші статті',
                    'cta_eyebrow'      => 'Потрібен senior engineer?',
                    'cta_title'        => 'Допомагаю командам оновлювати продукти, прискорювати платформи та запускати якісніші рішення.',
                    'cta_body'         => 'Від архітектури та Laravel-бекендів до фронтенду, SEO-підготовленого контенту й інженерних процесів.',
                    'cta_primary'      => 'Зв\'язатися',
                    'cta_secondary'    => 'Переглянути кейси',
                    'author_title'     => 'Про автора',
                    'author_body'      => 'Senior Full-Stack Engineer з досвідом 10+ років у SaaS, мультимовних контент-платформах і сучасних веб-продуктах.',
                    'share_title'      => 'Поділитися статтею',
                    'next_article'     => 'Наступна стаття',
                    'previous_article' => 'Попередня стаття',
                    'explore_more'     => 'Дивіться також',
                    'footer_text'      => 'Мультимовне портфоліо, кейси та технічні статті.',
                ],
                'es' => [
                    'breadcrumbs'      => 'Migas de pan',
                    'post_nav'         => 'Navegación de la página del artículo',
                    'blog_article'     => 'Artículo del blog',
                    'published'        => 'Publicado',
                    'updated'          => 'Actualizado',
                    'reading_time'     => 'min de lectura',
                    'toc'              => 'En esta página',
                    'recent_posts'     => 'Más artículos',
                    'cta_eyebrow'      => '¿Necesitas un senior engineer?',
                    'cta_title'        => 'Ayudo a los equipos a modernizar productos, mejorar el rendimiento y lanzar plataformas más limpias.',
                    'cta_body'         => 'Desde arquitectura y backends en Laravel hasta frontend, contenido listo para SEO y flujos de desarrollo.',
                    'cta_primary'      => 'Hablemos',
                    'cta_secondary'    => 'Ver proyectos',
                    'author_title'     => 'Sobre el autor',
                    'author_body'      => 'Senior Full-Stack Engineer con más de 10 años de experiencia en productos SaaS, plataformas multilingües de contenido y aplicaciones web modernas.',
                    'share_title'      => 'Compartir este artículo',
                    'next_article'     => 'Siguiente artículo',
                    'previous_article' => 'Artículo anterior',
                    'explore_more'     => 'Explorar más',
                    'footer_text'      => 'Portafolio multilingüe, casos prácticos y artículos técnicos.',
                ],
            ],
            'archive' => [
                'en' => [
                    'read_more' => 'Read article',
                    'no_posts'  => 'No articles found in this category.',
                    'older'     => 'Older articles',
                    'newer'     => 'Newer articles',
                ],
                'ru' => [
                    'read_more' => 'Читать статью',
                    'no_posts'  => 'В этой категории пока нет статей.',
                    'older'     => 'Старые статьи',
                    'newer'     => 'Новые статьи',
                ],
                'uk' => [
                    'read_more' => 'Читати статтю',
                    'no_posts'  => 'У цій категорії поки немає статей.',
                    'older'     => 'Старіші статті',
                    'newer'     => 'Новіші статті',
                ],
                'es' => [
                    'read_more' => 'Leer artículo',
                    'no_posts'  => 'No hay artículos en esta categoría.',
                    'older'     => 'Artículos anteriores',
                    'newer'     => 'Artículos más recientes',
                ],
            ],
            'errors' => [
                'en' => [
                    '404_title'         => 'Page not found',
                    '404_text'          => 'The page you are looking for does not exist or has been moved.',
                    'search_eyebrow'    => 'Search results',
                    'search_found'      => 'Found %d results',
                    'search_empty'      => 'No results found for your query.',
                    'search_suggestion' => 'Try a different search term, or explore the links below.',
                ],
                'ru' => [
                    '404_title'         => 'Страница не найдена',
                    '404_text'          => 'Запрашиваемая страница не существует или была перемещена.',
                    'search_eyebrow'    => 'Результаты поиска',
                    'search_found'      => 'Найдено результатов: %d',
                    'search_empty'      => 'По вашему запросу ничего не найдено.',
                    'search_suggestion' => 'Попробуйте другой запрос или воспользуйтесь ссылками ниже.',
                ],
                'uk' => [
                    '404_title'         => 'Сторінку не знайдено',
                    '404_text'          => 'Сторінка, яку ви шукаєте, не існує або була переміщена.',
                    'search_eyebrow'    => 'Результати пошуку',
                    'search_found'      => 'Знайдено результатів: %d',
                    'search_empty'      => 'За вашим запитом нічого не знайдено.',
                    'search_suggestion' => 'Спробуйте інший запит або скористайтеся посиланнями нижче.',
                ],
                'es' => [
                    '404_title'         => 'Página no encontrada',
                    '404_text'          => 'La página que buscas no existe o ha sido movida.',
                    'search_eyebrow'    => 'Resultados de búsqueda',
                    'search_found'      => 'Se encontraron %d resultados',
                    'search_empty'      => 'No se encontraron resultados para tu búsqueda.',
                    'search_suggestion' => 'Prueba con otro término de búsqueda o explora los enlaces a continuación.',
                ],
            ],
        ],
    ];
}
